### ISSUE TITLE
[NFR] Pass OutputInterface to consumer

### ISSUE THREAD

**Issue by sirian** [php-amqplib/RabbitMqBundle#104]
Provide a way to pass OutputInterface to consumer

**Comment by greg0ire** [comment]
I would like the same thing : there is this `liip:imagine:cache:resolve` I need to call from my Consumer, and it needs an output instance. I can of course provide a mock, but providing the real output would be even better.

**Comment by ramunasd** [comment]
You can create a new OutputInterface in Your callback. There is no big difference.
