### ISSUE TITLE
[Feature request] Support for configuring with an amqp uri

### ISSUE THREAD

**Issue by stof** [php-amqplib/RabbitMqBundle#113]
It would be great if the config could accept an [amqp uri](http://www.rabbitmq.com/uri-spec.html) and convert it internally to extract each setting. This would make it easier to use the bundle with hosted rabbitmq providing an amqp uri with the settings (for instance, CloudAMQP sets the uri directly as an environment variable on heroku)

**Comment by t0k4rt** [comment]
:+1:

**Comment by ramunasd** [comment]
Already implemented.
