### ISSUE TITLE
Can't connect consumer to localhost RabbitMQ with --env=prod

### ISSUE THREAD

**Issue by quantizer** [php-amqplib/RabbitMqBundle#123]
I install rabbitMQ 3.1.3 on ubuntu 12.04 and started server without any configuration and try to start consumers, but it works only, when i use debug flag -d, like this `php .../app/console rabbitmq:consumer -w -d consumer_name` and not working on production server without `-d` and with `--env=prod`, return exception 

```
[PhpAmqpLib\Exception\AMQPRuntimeException]             
Error Connecting to server(110): Connection timed out
```

or

```
[PhpAmqpLib\Exception\AMQPRuntimeException]         
Error Connecting to server(113): No route to host
```

Details and logs, see at [stackoverflow](http://stackoverflow.com/questions/17426899/client-cant-connect-to-rabbitmq-server-on-localhost)

**Comment by gossip1212** [comment]
I love the way you write and share your niche! Very interesting and different! Keep it coming! [
]([url](https://talksgossip.com/
))

**Comment by gossip1212** [comment]
I really appreciate this wonderful post that you have provided for us. I assure this would be beneficial for most of the people. <a href="https://talksgossip.com/">Conversation</a>
