### ISSUE TITLE
RPC callbacks: implementing the "random_int_server".

### ISSUE THREAD

**Issue by morafabio** [php-amqplib/RabbitMqBundle#142]
I'm reading the RPC Readme section (https://github.com/videlalvaro/RabbitMqBundle#rpc-or-replyresponse), but I can't figure out on how to implement the `random_int_server` _callback_.

I mean: is there any `RpcServerInterface`, so I need to extend the `RpcServer` class or something else?

Can someone make an example on how to define and implement the `old_sound_rabbit_mq.random_init_server` service?

Thanks.

**Comment by j0k3r** [comment]
@plfort That's a good start, do you have an example to share?

**Comment by bogomya** [comment]
j0k3r, +1
