### ISSUE TITLE
Firing some events when running a command

### ISSUE THREAD

**Issue by Taluu** [php-amqplib/RabbitMqBundle#147]
When using RabbitMQ with Symfony (as this is the goal of this bundle), I think it would be kinda useful to allow to trigger some determined event when receiving a message through a consumer (something like `BEFORE_TREATMENT`, `AFTER_TREATMENT` which would be respectively fired before the callback is called for messages and after it is called, which would get the result returned ?)

I'll try to see if I can make a PR of some sort if the idea could be useful

**Comment by Keloo** [comment]
+1 waiting for the feature.

**Comment by videlalvaro** [comment]
I would consider a PR if someone wants to implement this feature
