### ISSUE TITLE
Timeout Error in consumer(fetch) messages

### ISSUE THREAD

**Issue by sandip2451984** [php-amqplib/RabbitMqBundle#156]
I am getting below error when I consume(fetch) messages from queue..

PHP Fatal error:  Uncaught exception 'PhpAmqpLib\Exception\AMQPTimeoutException' with message 'A timeout occurs while waiting for incoming data' in

 I have used below code

$callback = function($msg) {
  return $msg->body;
};

$var = $channel->basic_consume('hello', '', false, true, false, false, $callback);

while(count($channel->callbacks)) {
    $channel->wait();
}

if i commented while loop than only one message is getting but I want to fetch all message which are in queue. so please suggest me on this error.

**Comment by ramunasd** [comment]
Just handle that timeout and repeat action. It's not connection timeout, rather just for action `wait()`.
https://github.com/php-amqplib/php-amqplib/blob/master/demo/amqp_message_headers_recv.php#L47
