### ISSUE TITLE
Consumer die , MySQL server has gone away 

### ISSUE THREAD

**Issue by pinouf** [php-amqplib/RabbitMqBundle#181]
hello,

i have a consumer on my server.
In this consumer, i use the service EntityManager.

During severals hours, there was not message in queue.
Next, i send message in queue .
When my consumer get the message, i got  a error MySQL server has gone away .
and my consumer process was killed.

How can i fix that?

thank you

**Comment by hackzilla** [comment]
Don't know when it was introduced, but there is a idle timeout setting now.

```
            idle_timeout:     1800
```
