### ISSUE TITLE
Dynamic consumer definition - works in dev, not in prod

### ISSUE THREAD

**Issue by spmasterman** [php-amqplib/RabbitMqBundle#196]
I'm using the DependencyInjection 'prepend' method, to dynamically generate the consumers part of the config. i.e.

old_sound_rabbit_mq:
    connections:
      ...
    producers:
      ...

my_config:
  consumers:
    <consumer config here>

and then in a DI extension class in my bundle, I'm finding the 'my_config -> consumers' config block, and appending it to the old_sound_rabbit_mq config block (with some runtime details filled in) 

 $container->prependExtensionConfig('old_sound_rabbit_mq', $consumerConfig);

It all works gloriously in Symfony debug mode. My services get created in the container, the consumers all work. In production mode however, it fails with the services not existing in the container, as if the extension isn't running, or the container is optimizing away my services or something. Is the creation of consumer services something that happens differently in dev and prod?

Is there perhaps some 'other' data structure somewhere I need to update if I do things this way? 

Any ideas at all on how to achieve this? (I'm happy to make changes to the bundle and pull request them so that this functionality is more widely supported - but not sure where to start?)

**Comment by tiborb** [comment]
But how to load consumers dynamically via a service, not just a config file. I can't seem to find a viable solution. Any ideas?

**Comment by spmasterman** [comment]
Not sure how you would do it dynamically in the general case. For me it was enough to implement the prepend method of the DependencyInjection/...Extension class, from I think PrependExtensionInterface - and use that method to effectively create my consumer definitions 'on the fly'. The only additional challenge was that the DB isn't available when that method gets called, so I had to cache the data I needed in a file. The fact that it was so tricky to achieve made me think I was taking the wrong approach in general (often the case!) - so although it worked, if I was doing it again, I'd look at why I thought I needed dynamically defined consumers, and try and design that requirement away.
