### ISSUE TITLE
[Feature Request] Events dispatched when grabbing a message, on exception, on ack, etc

### ISSUE THREAD

**Issue by adicosoi** [php-amqplib/RabbitMqBundle#201]
Hello,

I think it will be a really useful feature if events ware dispatched on key point in the consumer.
1. Being able to log all messages consumed
2. Being able to stop exeptions from shooting down your consumer,  grab and ack the message

The consumer is an ongoing command, and the symfony 2 command event don't help because the amqp message can't be accessed from those events

Thank you.

**Comment by reggin** [comment]
Also, very need event onBeforePublish - some values must be in each message (user_id, for example).

**Comment by videlalvaro** [comment]
Aren't these issues related? https://github.com/videlalvaro/RabbitMqBundle/issues/147

Also keep in mind that anything you do during publish will affect performance.

**Comment by ramunasd** [comment]
Implemented. Please see:
https://github.com/php-amqplib/RabbitMqBundle/blob/master/RabbitMq/Consumer.php#L143
