### ISSUE TITLE
rabbitmq:multiple-consumer not respecting the --messages and and --memory-limit options unless --route is also specified 

### ISSUE THREAD

**Issue by nedlukies** [php-amqplib/RabbitMqBundle#229]
I have a multiple consumer with the following configuration. A multiple consumer was used as I assumed this would allow one process to consume information from multiple queues, rather than having to run three separate concurrent processes

```
multiple_consumers:
    trigger:
      connection:   default
      exchange_options: {name: 'trigger', type: direct}
      queues:
          trigger-event:
            name:     trigger-event
            callback: trigger_event_service
            routing_keys:
                - event
          trigger-segment-update:
            name:     trigger-segment-update
            callback: trigger_segment_update_service
            routing_keys:
                - segment_update
          trigger-profile-update:
            name:     trigger-profile-update
            callback: trigger_profile_update_service
            routing_keys:
                - profile_update
```

I have setup the process to run using daemontools, which keeps the process alive and restarts it when required, however when using the following command, the process continues to process more than 10 messages and never exits:

`app/console --env=prod -v rabbitmq:multiple-consumer -m 10  trigger`

Similarly, if I specify a memory limit, the process continues to grow in size (currently 740mb, and 100%): 

`app/console --env=prod -v rabbitmq:multiple-consumer -l 64 -m 100 trigger`

I can specify the --route option with one of the configured routing keys (profile_update, segment_update, or event), and the process will exit after processing the specified number of messages, yet this would require three separate processes and I might as well just configure them as normal consumers. Is this the expected behaviour? I understand that the memory leak and cpu utilisation is the result of Doctrine and not rabbitmq-bundle, hence why I want the process to restart regularly. Should the -m and -l options work with a multiple consumer or only when the -r option is also specified?

**Comment by mariuszgil** [comment]
+1

**Comment by mariuszgil** [comment]
@nedlukies Update bundle version to: "oldsound/rabbitmq-bundle": "1.6.*@dev". Mentioned in bundle documentation version 1.* hasn't got method for stopping multiple consumer.

**Comment by stalxed** [comment]
Its work in master now?
