### ISSUE TITLE
Define consumers dynamically

### ISSUE THREAD

**Issue by AdamBoxall** [php-amqplib/RabbitMqBundle#234]
I can't tell from the docs whether there's a way to dynamically define the list of consumers? There's a way to define the queues dynamically under `multiple_consumers`, but it would be nice to have a way of dynamically generating standard consumers.

**Comment by tiborb** [comment]
Same problem here, maybe the bundle could be extened to add a consumers provier. Any thoughts?

**Comment by AdamBoxall** [comment]
Well my aim was to be able to define queues programmatically from a database with a unique routing key for each, and then generate a Symfony consumer service for each queue.

You can already define the queues for a consumer using the `queue_provider` configuration option, so something like that would work well I think? That project has come and gone now, but would be willing to try at adding in this support if it's going to be helpful to others.

**Comment by tiborb** [comment]
The consumers are defined in the OldSoundRabbitMqExtension directly from the bundle config. I don't see how a provider can be added here :/

**Comment by tiborb** [comment]
Here's the idea: 
Adding a 'rabbitmq:dynamic-consumer' command and a DymanicConsumer class, similar to MultipleConsumer, which will get the consumers using a provider. 
The provder will return the consumer name, queue options and routing key.

Usage Example:
app/console rabbitmq:dynamic-consume consumer_loaded_via_provider

If the user attempts to start the command for a non exsting consumer an exception will be thrown and the error could be handled.

**Comment by tiborb** [comment]
I proposed this as a feature:https://github.com/videlalvaro/RabbitMqBundle/issues/264

**Comment by tiborb** [comment]
Hey Adam, i have implemented this feature, you can have a look at it https://github.com/videlalvaro/RabbitMqBundle/pull/266

**Comment by videlalvaro** [comment]
This have been merged. If this satisfies your needs, @AdamBoxall please close the issue

**Comment by omarfawzi** [comment]
@videlalvaro where have this been merged ?
