### ISSUE TITLE
Ack message message before consumer executes

### ISSUE THREAD

**Issue by gedimin45** [php-amqplib/RabbitMqBundle#248]
Hey!

Thanks for the bundle, great work!
Currently the way the bundle is set up I do not see a way to ack message before actually executing the consumer.
Consider a use case where the consumer sends an email when it receives a message. Let's say something goes wrong just after sending the message and the consumer crashes. The message is going to be requeued and another consumer is going to receive it. The email is going to be sent again and if the crashes keep happening a huge amount of unwanted email will be sent.
To avoid the described situation we could ACK (or reject) the message as soon as it arrives and do the processing after.
Is it intentional that this feature is not present? Do you see a better solution for the situation? Or perhaps I overlooked something and this is possible with the current bundle?

**Comment by ged15** [comment]
It seems we can also set the ```no_ack``` parameter in ```basic_consume``` to ```true``` (https://github.com/videlalvaro/RabbitMqBundle/blob/master/RabbitMq/BaseConsumer.php#L43) and that should do the trick. Is this correct? :)

**Comment by calumbrodie** [comment]
I'm also trying to figure this out - the issue for me is that in OldSound/RabbitMqBundle/RabbitMq/Consumer::processMessage

The callback can (theoretically) cause a fatal error (not exception) which cannot be elegantly handled.
Obviously this isn't an issue for all codebases - but in those that it might be it would be good to have a clear configuration to handle that, either by acknowledging the message before processing or by changing the exchange to remove the message after being sent to the consumer (if that is possible).
