### ISSUE TITLE
Strange race conditions

### ISSUE THREAD

**Issue by ghost** [php-amqplib/RabbitMqBundle#252]
Hi,

I cant wrap my head around this, might not be a bug though but i'm only experiencing it using consumers..

When i flush and commit a transaction for entity A with a property `active` = true, and queue a message to process this entity AFTER this, then fetching the same entity in the consumer simply does not get the changed status. No result cache.

It gets funnier, if i return false in the consumer, and refetch the entity untill that active status matches true, to which i set it to in the producer so it keeps putting the message back in the queue to check if its a race condition. It just loops endlessly UNTILL i quit the consumer and restart it, its only after this that the status is actually changed.. Really, WHAT.

If i let it loop it even shows the query log full of infinite queries fetching the entity, any ideas?

**Comment by videlalvaro** [comment]
What entities are you talking about? If this is related to Doctrine or something similar, I can't answer those questions.

**Comment by mvrhov** [comment]
It's not a race condition. It's a simple fact that PHP is run in shared nothing architecture, so after your script is done processing php releases al variables. Hovewer your producer is long running process. Doctrine remembers the entities it fetched. If you fetch it again it will return the one it cached.
What you must do is detach the objects once you are done with them, or better clear doctrine managers at the beginning of a execute function of your consumer
