### ISSUE TITLE
Suggestion : put bindings in a separate configuration block 

### ISSUE THREAD

**Issue by monsieurchico** [php-amqplib/RabbitMqBundle#253]
Hi,

I'm using your bundle and first of all, great job !
But I don't understand how to easily create a configuration for producers and consumers.
For instance, a consumer must declare an "exchange_options". I ain't sure it respects the rabbitmq logic.

When you export your configuration from the manager your obtain something like this :

``` javascript
"queues": [{
        "name": "myQueue1",
        "vhost": "/",
        "durable": true,
        "auto_delete": false,
        "arguments": {}
    }
],
"exchanges": [{
        "name": "myExchange1",
        "vhost": "/",
        "type": "direct",
        "durable": true,
        "auto_delete": false,
        "internal": false,
        "arguments": {}
    }
],
 "bindings": [{
        "source": "myExchange1",
        "vhost": "/",
        "destination": "myQueue1",
        "destination_type": "queue",
        "routing_key": "",
        "arguments": {}
    }
]
```

I think it could be an interesting enhancement to adopt this kind of configuration. It brings more clarity (to my mind :))

**Comment by videlalvaro** [comment]
I don't understand what's the issue.

What do you mean by: 

>I ain't sure it respects the rabbitmq logic.

**Comment by monsieurchico** [comment]
Hi.
I'm sorry it came out wrong. I was only suggesting that the binding got its own configuration instead of being put into the queue options. It would bring more clarity.
