### ISSUE TITLE
Implement worker with consumer

### ISSUE THREAD

**Issue by Sukhrob** [php-amqplib/RabbitMqBundle#279]
What are the consequences of doing this:

```
public function execute(AMQPMessage $message)
{
    while (true) {
        // Do some heavy work here (Example: retrieve the last 50 items from the database and update their states, etc)

        sleep(2); // Sleep for 2 seconds
    }

    return true; // Acknowledge (Never executed)
}
```
1. One unacknowledged message (Bad)
2. Max execution time of PHP script (But, it works perfectly and is never ending even though phpinfo shows 60 seconds)
3. Any more issues

http://stackoverflow.com/questions/31026681/implement-worker-with-rabbitmq-consumer

Thanks

**Comment by tiborb** [comment]
- if you need to do some heavy work, you can do it in your callback service can use a standard consumer
- why do you even need rabbitmq+bundle for an infinite loop when you can use a console command and maybe supervisor

Can you please explain the use case for this?

**Comment by tiborb** [comment]
This issue seems to be outdated, closing
