### ISSUE TITLE
Conflicting documentation in ConsumerInterface

### ISSUE THREAD

**Issue by Phobetor** [php-amqplib/RabbitMqBundle#287]
`OldSound\RabbitMqBundle\RabbitMq\ConsumerInterface` provides some constants to use as return values for its `execute` method:
- (1) Flag for message ack
- (2) Flag single for message nack and requeue
- (0) Flag for reject and requeue
- (-1) Flag for reject and drop

`execute`'s return value documentation states "false to reject and requeue, any other value to acknowledge". Considering the constants this cannot be correct.

**Comment by videlalvaro** [comment]
Do you mind sending a PR to update the docs?

**Comment by ramunasd** [comment]
fixed
