### ISSUE TITLE
[Suggestion] There are too many (and too old) open issues in the tracker

### ISSUE THREAD

**Issue by castarco** [php-amqplib/RabbitMqBundle#289]
Hi,

As a user of RabbitMqBundle, it's a little bit annoying seeing too many open issues without response and without labels, a lot of them existing since 2011 or 2012.

It makes difficult to know what are the real problems of the current version.

**Comment by videlalvaro** [comment]
Feel free to answer/close/mark resolved those you deem appropriate. I'm on holidays at the moment.
