### ISSUE TITLE
Create rpc server

### ISSUE THREAD

**Issue by ghost** [php-amqplib/RabbitMqBundle#29]
Hi,
I want to write a rpc server and I found that the document only mentioned rpc client,
I read the source code and guessed the way to write rpc server is to write a callback "function"
which is defined in service.yml, but in this way I would get a "object", not "function".

Thanks in advanced.

**Comment by devckonem** [comment]
Maybe this helps: http://www.inanzzz.com/index.php/post/2uco/rabbitmq-remote-procedure-call-example-with-symfony
