### ISSUE TITLE
Consumer architecture

### ISSUE THREAD

**Issue by pluff** [php-amqplib/RabbitMqBundle#30]
Hello @videlalvaro 

I review your bundle a bit and I have couple of issues.
1. Does producer should know anything about queues? As far as I understand producer just publishes messages to exchange. The only thing producer should declare is an exchange.
2. Does consumer should know anything about exchanges and routing keys? As far as I understand consumer just consumes the message from a queue and doesn't care where it come from. The only thing consumer should declare is a queue he consumes.
3. If both questions above should be answered "no" then we need a way to setup exchanges,queues and bindings between them and here comes my issue #27. I can implement these changes, but I just need your opinion maybe I have missed something important.

**Comment by castarco** [comment]
Why there are open issues since 2012 and with no response?

**Comment by videlalvaro** [comment]
@castarco replied in another issue. Cheers
