### ISSUE TITLE
connexion closed, server rpc

### ISSUE THREAD

**Issue by pinouf** [php-amqplib/RabbitMqBundle#308]
hello,

i got  a server rpc server which consume messages that client rpc send.
that's work perfectly but sometimes the server rpc down ( it is random ).

the error is a connexion closed.
how can i fix it?

  [PhpAmqpLib\Exception\AMQPRuntimeException]  
  Broken pipe or closed connection             

rabbitmq:rpc-server [-m|--messages[="..."]] [-d|--debug[="..."]] name

PHP Fatal error:  Uncaught exception 'PhpAmqpLib\Exception\AMQPRuntimeException' with message 'Broken pipe or closed connection' in /var/www/newconvert.kadrige.com/vendor/videlalvaro/php-amqplib/PhpAmqpLib/Wire/IO/StreamIO.php:174
Stack trace:
#0 /var/www/newconvert.kadrige.com/vendor/videlalvaro/php-amqplib/PhpAmqpLib/Connection/AbstractConnection.php(387): PhpAmqpLib\Wire\IO\StreamIO->write('\x01\x00\x01\x00\x00\x00\v\x00\x14\x00(\x00\x00\x00\x00...')
#1 /var/www/newconvert.kadrige.com/vendor/videlalvaro/php-amqplib/PhpAmqpLib/Connection/AbstractConnection.php(498): PhpAmqpLib\Connection\AbstractConnection->write('\x01\x00\x01\x00\x00\x00\v\x00\x14\x00(\x00\x00\x00\x00...')
#2 /var/www/newconvert.kadrige.com/vendor/videlalvaro/php-amqplib/PhpAmqpLib/Channel/AbstractChannel.php(191): PhpAmqpLib\Connection\AbstractConnection->send_channel_method_frame(1, Array, Object(PhpAmqpLib\Wire\AMQPWriter))
#3 /var/www/newconvert.kadrige.com/vendor/videlalvaro/php-amqplib/PhpAmqpLib/Channel/AMQPChannel.php(199): PhpAmqpLib\Channel\Abstra in /var/www/newconvert.kadrige.com/vendor/videlalvaro/php-amqplib/PhpAmqpLib/Wire/IO/StreamIO.php on line 174

thank you -)

**Comment by ramunasd** [comment]
This looks like ibrary issue. Please report there if it still occurs.
