### ISSUE TITLE
Better documentation for the ConsumerInterface constants

### ISSUE THREAD

**Issue by Drachenkaetzchen** [php-amqplib/RabbitMqBundle#311]
Hi,

I'm wondering what exactly the `ConsumerInterface` constants do, especially the difference between `MSG_SINGLE_NACK_REQUEUE` and `MSG_REJECT_REQUEUE` is not obvious to me. `MSG_ACK` and `MSG_REJECT` is obvious to me.

I have looked at several docs from RabbitMQ and Googled, but couldn't find an answer to that question.

**Comment by ramunasd** [comment]
Just take a look at official documentation.
https://www.rabbitmq.com/confirms.html
