### ISSUE TITLE
Options to make consumer terminate

### ISSUE THREAD

**Issue by mlmarius** [php-amqplib/RabbitMqBundle#316]
Hi. I want to make the consumer terminate itself once it has processed 50 messages or once there are no more messages currently in the queue. There is the -m option to limit message count but how do i make it terminate once the messages have finished before reaching the defined limit?

**Comment by Sander-Toonen** [comment]
+1 This feature would enable people to run a consumer on cron, instead of as a daemon.

**Comment by bburnichon** [comment]
You can already make a consumer terminate itself. I had the same requirement a while ago. You should make your consumer implement [`OldSound\RabbitMqBundle\RabbitMq\DequeuerAwareInterface`](https://github.com/videlalvaro/RabbitMqBundle/blob/master/RabbitMq/DequeuerAwareInterface.php). Then, you can use [`OldSound\RabbitMqBundle\RabbitMq\DequeuerInterface`](https://github.com/videlalvaro/RabbitMqBundle/blob/master/RabbitMq/DequeuerInterface.php) to have your consumer kill itself on whatever condition.

**Comment by ramunasd** [comment]
Just throw StopConsumerException
