### ISSUE TITLE
Default exchange for Consumers

### ISSUE THREAD

**Issue by theUniC** [php-amqplib/RabbitMqBundle#317]
Hi,

First of all would like to thank you for this awesome bundle. It's really useful and greatly simplifies the usage of RabbitMQ from Symfony.

I open this issue because would like to know if there is any reason to not to configure a default exchange for consumers (like for **[producers](https://github.com/videlalvaro/RabbitMqBundle/blob/master/DependencyInjection/OldSoundRabbitMqExtension.php#L107)**).

Would be this an interesting feature for the bundle?

Thanks in advance!
Christian.

**Comment by blanchonvincent** [comment]
Hey

I have a question related to yours.

Why do we even need specify exchange options in the consumer options? Since the exchanges dispatch messages to the queue, and the consumer is related to the queue only, why do we need to link the exchange and the consumer?
