### ISSUE TITLE
[Doc] Multiple Consumers -- discrepancy, unclear

### ISSUE THREAD

**Issue by lemoinem** [php-amqplib/RabbitMqBundle#322]
The documentation for Multiple Consumers is at least unclear, at most contradictory.

The first paragraph (after the config example) reads:

> The callback is now specified under each queues and must implement the ConsumerInterface like a simple consumer.

But the last paragraph reads:

> callbacks are callables (not ConsumerInterface)

Am I missing something?

**Comment by aashley** [comment]
The last paragraph is talking about the optional queues_provider functionality, the paragraph needs some work but you can ignore that option when implementing a multiple consumer.
