### ISSUE TITLE
Get queue message count

### ISSUE THREAD

**Issue by SouthOfWest** [php-amqplib/RabbitMqBundle#326]
Is it possible, now?

**Comment by Enleur** [comment]
http://php.net/manual/fa/amqpqueue.declare.php returns the message count

**Comment by grekpg** [comment]
```
AMQPQueue::declareQueue();

Attempted to load class "AMQPQueue" from the global namespace.
Did you forget a "use" statement?
```

this bundle cant read get count messages using loggin details from parameters ?

**Comment by damianprzygodzki** [comment]
This works also, basic_get without acknowledging.

```
// $this->consumer = self::$kernel->getContainer()->get('old_sound_rabbit_mq.default_consumer');
count($this->consumer->getChannel()->basic_get('lottofun.lcr.betting', false))
```

**Comment by bloodmarch** [comment]
With "php-amqplib/rabbitmq-bundle": "1.14.4",

connection = new AMQPStreamConnection('localhost', 5672, 'root', '123');
$channel = $connection->channel();
list($queue, $messageCount, $consumerCount) = $channel->queue_declare('ppm-parse', true);

Throw an exception : 
![image](https://user-images.githubusercontent.com/13070703/117629143-246a3a00-b17a-11eb-8d84-4a6e80935814.png)

Is there any way to know how many messages are in queue ?
