### ISSUE TITLE
Find a new maintainer for the project

### ISSUE THREAD

**Issue by videlalvaro** [php-amqplib/RabbitMqBundle#327]
As you might know, I'm leaving the company that makes RabbitMQ https://groups.google.com/forum/#!topic/rabbitmq-users/-byffkRnI2w, so I will have even less time to take care of this project. Therefore I'm opening this issue so the community helps with finding a new maintainer(s) for the project.

While I would like to have a stronger say on who should take care of the project, I would ask contributors and users to propose who you think would be a great candidate. Please comment on this issue and help find that person.

Besides from knowing PHP, you must be very familiar with at least these concepts: http://www.rabbitmq.com/tutorials/amqp-concepts.html

**Comment by ChristianRiesen** [comment]
Same interest here as for the lib itself :)

**Comment by stloyd** [comment]
Hey, I would like to help here as in current project we use quite extensive the RabbitMQ (along with this bundle & library), for sure I'm not an expert in case of RabbitMQ it self, but I'm still learning & extend the usage of it in current project.

I'm one of the persons behind quite popular: [https://github.com/hwi/HWIOAuthBundle/graphs/contributors](HWIOAuthBundle) (which is a bit "abonded" due to fact that in current job we use only JWT, not the OAuth approach, but that's not the topic for this issue :))

Feel free to ping me (mail is shown at profile page)!

ps. Thanks for all the years spent on doing great job with helping community & have fun at new job!

**Comment by mariotux** [comment]
Hello,

I'm not an expert in RabbitMQ but we use this bundle in our project and I have interest to continue to using this bundle, I can help.

**Comment by tiborb** [comment]
Hey @videlalvaro , 

the company that I am working for is using the bundle as a mission critical component.
I am familiar with AMQP & RabbitMQ and I'm willing to maintain the Bundle.

Cheers,
Tibor

**Comment by videlalvaro** [comment]
thanks @tiborb and everyone else for offering support. I think by next Monday we can see who has volunteered and then between everyone you can start taking care of the project.

**Comment by skafandri** [comment]
Hello,
I make extensive use of this bundle, I am fluent in PHP and Symfony ecosystem (contributor). I have good understanding of AMQP concepts.
I volunteer to be one of the future maintainers.

**Comment by videlalvaro** [comment]
@skafandri @tiborb @mariotux @stloyd @ChristianRiesen so do you want to be added as maintainers?

**Comment by skafandri** [comment]
@videlalvaro I confirm.

**Comment by videlalvaro** [comment]
@skafandri added you, let's wait for the others, and then let's see if we move the bundle to the php-amqplib org created here: https://github.com/php-amqplib

**Comment by skafandri** [comment]
What about packagist? https://packagist.org/packages/oldsound/rabbitmq-bundle I think we have 2 options:

1. Create a new name **php-amqplib/rabbitmq-bundle**? And make the old package suggest the new one.
2. Re-enable oldsound/rabbitmq-bundle

**Comment by videlalvaro** [comment]
Probably moving the project to a new org makes more sense

**Comment by mariotux** [comment]
I'll do as possible to help

**Comment by stloyd** [comment]
Yep, still here to help, also that repo move sounds reasonable for me.

**Comment by tiborb** [comment]
@videlalvaro check

**Comment by videlalvaro** [comment]
@postalservice14 can we move the bundle into the php-amqplib org? What do you suggest? This bundle depends on the lib

**Comment by postalservice14** [comment]
@videlalvaro I think it makes perfect sense to do that.  Feel free....

**Comment by tiborb** [comment]
I agree, php-amqplib would be a more generic org

**Comment by videlalvaro** [comment]
Cool, I'll transfer the package there

**Comment by videlalvaro** [comment]
BTW, with the people at the php-amqplib organization we are discussing about adopting the Contributor Covenant CoC. What do the others on this bundle think? That CoC will almost certainly be adapted by the php-amqplib project

**Comment by zerkms** [comment]
@videlalvaro just adopt the most widely used one. Any suggestion to discuss it will lead to many weeks of bikeshedding.
