### ISSUE TITLE
Change base namespace to PhpAmqpLib

### ISSUE THREAD

**Issue by postalservice14** [php-amqplib/RabbitMqBundle#332]
Now that the `RabbitMqBundle` is a part of the `php-amqplib` organization, it might be good to change the base namespace from `OldSound` to `PhpAmqpLib`.  The problem is that this would be a BC break, so you would have to make that happen during the next major release.  But just wanted to start the discussion here...

**Comment by stloyd** [comment]
This would be rally big BC break, TBH. I'm not sure it's worth it... at least for now.

IMO would be better to get "everything" fixed/merged that is waiting etc. and then think after that about such moves.

Just my 2 cents ;)

**Comment by postalservice14** [comment]
@stloyd Yeah, that is true.  It's fine if it's not something to do now, just something to throw in the backlog.

**Comment by JarJak** [comment]
+1 for doing this next major release (2.0)

**Comment by perajovic** [comment]
Also we can manage some migration script as well.

**Comment by ramunasd** [comment]
It would be very big and breaking change. Not planned any time soon AFAIK.
