### ISSUE TITLE
Tag new version which uses php-amqplib/php-amqplib

### ISSUE THREAD

**Issue by JarJak** [php-amqplib/RabbitMqBundle#341]
Actual version in packaigst still uses abandoned videalvaro/php-amqplib:
https://packagist.org/packages/php-amqplib/rabbitmq-bundle

**Comment by stloyd** [comment]
Just tagged version `1.9.0` - https://github.com/php-amqplib/RabbitMqBundle/releases/tag/v1.9.0

**Comment by JarJak** [comment]
thanks
