### ISSUE TITLE
Detailed documentation and explanation about configuration values

### ISSUE THREAD

**Issue by skafandri** [php-amqplib/RabbitMqBundle#364]
read_write_timeout, heartbeat...

**Comment by BentCoder** [comment]
Do you mind adding "keep alive" as well please? Thank you very much in advance. I'll read every bit of it carefully.

**Comment by skafandri** [comment]
I will try to cover as many configurations as possible. Please comment here with any suggestions.

**Comment by BentCoder** [comment]
I opened [this issue](https://github.com/php-amqplib/RabbitMqBundle/issues/328) long time back but didn't find a working example so if you could help me out with that, I will be happy. Only if you have a time though so no rush at all.
