### ISSUE TITLE
How to bind two exchanges to the same callback ?

### ISSUE THREAD

**Issue by syrm** [php-amqplib/RabbitMqBundle#367]
Hello,

How can i bind two exchanges to the same callback ?

```
old_sound_rabbit_mq:
    producers:
        broadcasting:
            exchange_options: {name: 'broadcasting', type: fanout}

        asyncprocess:
            exchange_options: {name: 'asyncprocess', type: fanout}

    consumers:
        broadcasting:
            exchange_options: {name: 'broadcasting', type: fanout}
            queue_options:    {name: 'asyncprocess'}
            callback:         asyncprocess_service

        asyncprocess:
            exchange_options: {name: 'asyncprocess', type: fanout}
            queue_options:    {name: 'asyncprocess'}
            callback:         asyncprocess_service
```

Only the last one is bind.

**Comment by aleixverges** [comment]
Good point I'm having the same issue here. Let's say I need to bind same topic from different exchanges.... What's the solution here? Of course, you can define two different queues per exchange, but then you'll end up in two different consumers registered in rabbit.

**Comment by syrm** [comment]
Up... ?

**Comment by giorgiosironi** [comment]
Same issue. It is quite possible to bind a single queue to multiple exchanges through the RabbitMQ UI, so I don't think it's an anti-pattern but an expected scenario. Using `exchange_options` for `consumers` seems to be weird in general, e.g. you may need to specify `type` even if `declare` is false.

**Comment by giorgiosironi** [comment]
I think you're meant to use [arbitrary bindings](https://github.com/php-amqplib/RabbitMqBundle#arbitrary-bindings), I'll try those.

**Comment by giorgiosironi** [comment]
That works for me, switch from using `exchange_options` to `bindings` at the configuration top-level.
