### ISSUE TITLE
Published message body empty

### ISSUE THREAD

**Issue by mcbuckets** [php-amqplib/RabbitMqBundle#370]
Hello,

i'm using 1.10 version of the bundle with Symfony2 2.4. 

I got the config and initial setup right but when i try to send objects to publish method i get empty message body. I'm trying to send two rather large entities and one SimpleXML object. To send them all in once i created some kind of Data Transfer Object, filled its properties with objects and tried to serialize it but in the consumer class i get the message body empty besides the encoded SimpleXML object.

This is the code i use:

//producer

```
$dataCollection->setTeam($team);
$dataCollection->setSeason($season);
$dataCollection->setTeamStats(json_encode($statsData->asXML()));

$this->container->get('myapp.soccer_team_stat.produce')->publish(json_encode($dataCollection));
```

//consumer
`$payload = json_decode($msg->body);`

What am i doing wrong and how can i publish multiple objects as message to consumer?

**Comment by skafandri** [comment]
What is the content of:
- var_dump(json_encode($dataCollection)) before bublishing
- var_dump($msg->body) in your consumer

PS: It would be a better approach to publish some sort of identifiers that you can use to fetch objects from a datastore or somewhere rather than publishing a full object.

**Comment by mcbuckets** [comment]
$dataCollection dump gives expected results meaning class properties as objects mentioned before. Dumping message body gives empty string. I considered using your approach but this way would be much cleaner since xml is extracted from api and structure is already defined. I think i'll have to modify my code to suit your proposal :)

**Comment by skafandri** [comment]
Try to dump json_encode($dataCollection) not $dataCollection (json_encode won't see private members)

````
class A
{
    private $a = 'a';
}
var_dump(json_encode(new A()));
````
string(2) "{}"

**Comment by mcbuckets** [comment]
Omg, of course..i switched to your proposal and it works now. My queue is filling but i don't see any work done. When are messages from queue supposed to be consumed? Right after execute method is called or after some time? 

http://monosnap.com/image/1lTAYGjac3z5jbIKeh3COArB80IWtk

**Comment by skafandri** [comment]
1. Is your consumer consuming messages? (they should disappear from Rabbit)
2. In the Rabbit web admin, you can check which processes are listening to a specific queue under the *consumers* section
3. Add some debugging to your consumer

**Comment by mcbuckets** [comment]
It works as expected..messages are consumed entirely. I have just one more question. When i add multiple consumers i get "You have requested a non-existent service "old_sound_rabbit_mq.soccer_person_stat_consumer" exception. My config looks like this:

```
old_sound_rabbit_mq:
    connections:
        default:
            host:     'localhost'
            port:     5672
            user:     'guest'
            password: 'guest'
            vhost:    '/'
            lazy:     false
            connection_timeout: 3
            read_write_timeout: 3

            # requires php-amqplib v2.4.1+ and PHP5.4+
            keepalive: false

            # requires php-amqplib v2.4.1+
            heartbeat: 0

            #requires php_sockets.dll
#            use_socket: true # default false
    producers:
        soccer_team_stat:
            connection:       default
            exchange_options: {name: 'soccer_team_stat_ex', type: direct}
    consumers:
        soccer_team_stat:
            connection:       default
            exchange_options: {name: 'soccer_team_stat_ex', type: direct}
            queue_options:    {name: 'soccer_team_stat_qu'}
            callback:         locastic.soccer_team_stat.consume
        soccer_team_stat_form:
            connection:       default
            exchange_options: {name: 'soccer_team_stat_ex', type: direct}
            queue_options:    {name: 'soccer_team_stat_qu'}
            callback:         myapp.soccer_team_stat_form.consume
        soccer_team_history:
            connection:       default
            exchange_options: {name: 'soccer_team_stat_ex', type: direct}
            queue_options:    {name: 'soccer_team_history_qu'}
            callback:         myapp.soccer_team_history.consume
        soccer_person_stat:
            connection:       default
            exchange_options: {name: 'soccer_team_stat_ex', type: direct}
            queue_options:    {name: 'soccer_person_stats_qu'}
            callback:         myapp.soccer_person_stat.consume
```
