### ISSUE TITLE
  PRECONDITION_FAILED - Invalid argument, 'x-delayed-type' must be an existing exchange type

### ISSUE THREAD

**Issue by TNAJanssen** [php-amqplib/RabbitMqBundle#381]
PRECONDITION_FAILED - Invalid argument, 'x-delayed-type' must be an existing exchange type

This error is solved by changing https://github.com/php-amqplib/RabbitMqBundle/blob/master/RabbitMq/BaseAmqp.php#L209 to new AMQPTable($this->exchangeOptions['arguments']),

**Comment by markitosgv** [comment]
Could someone check this? I want to use a x-delayed-type exchange

**Comment by andreyors** [comment]
You need to configure a rabbitmq server to enable that feature

**Comment by michielgerritsen** [comment]
I got around this error by declaring my exchange like this:
```
exchange_options: {name: 'exchange_name', type: 'x-delayed-message', arguments: {'x-delayed-type': ['S', 'direct']}}
```
