### ISSUE TITLE
Symfony 3 deprecation warnings

### ISSUE THREAD

**Issue by wikimatze** [php-amqplib/RabbitMqBundle#384]
Hi,

I'm right in the middle of updating my Symfony projects, running the `deprecation-detector.phar` on the master of this projects gives me the following message:

``` sh
| 2 | Calling deprecated method Symfony\Component\DependencyInjection\Definition->setFactoryService()                           | 94   | since version 2.6, to be removed in 3.0. |
| 3 | Calling deprecated method Symfony\Component\DependencyInjection\Definition->setFactoryMethod()                            | 95   | since version 2.6, to be removed in 3.0. |
```

Are there any plans to get refactor this code?

Cheers,

Matthias

**Comment by KingCrunch** [comment]
That is already related to a compatibility layer I guess

https://github.com/php-amqplib/RabbitMqBundle/blob/master/DependencyInjection/OldSoundRabbitMqExtension.php#L89-L96

**Comment by ramunasd** [comment]
Supported Symfony versions are 4.3 and up.
