### ISSUE TITLE
Run RabbitMQ Consumers without HttpKernel and FrameworkBundle

### ISSUE THREAD

**Issue by CEngelbert** [php-amqplib/RabbitMqBundle#385]
As I am trying to develop an Application with Symfony, I wanted to run my RabbitMQ Consumers without the need of loading the HttpKernel and the FrameworkBundle.

So I read this part of the documentation:
[https://github.com/php-amqplib/RabbitMqBundle#for-a-console-application-that-uses-symfony-console-dependency-injection-and-config-components](url)

But I do not understand where I have to register the OldSoundRabbitMqExtension and add the Compiler Pass.

**Comment by ramunasd** [comment]
I don't it's possible to run bundle without framework :)
