### ISSUE TITLE
Support of NewRelic

### ISSUE THREAD

**Issue by JonasHaouzi** [php-amqplib/RabbitMqBundle#386]
### Explanation

When using NewRelic, the consumers processes are reported under the name: `rabbitmq:consumer` which is not really explicit.
The main problem is that all the consumers are grouped together and analysing them can be quite difficult.
### Suggestion

Many Symfony developers are using the bundle [ekino/EkinoNewRelicBundle](https://github.com/ekino/EkinoNewRelicBundle).
We could automatically detect if this bundle is installed, and if so, set the transaction name to something like: `Consumer (Consumer Name Here)`
### Screenshots

In the NewRelic dashboard, instead of having:
<img width="895" alt="before" src="https://cloud.githubusercontent.com/assets/8245107/18581374/8f4bb394-7c00-11e6-86a9-2c2ea224e2b1.png">

we would have:
<img width="892" alt="after" src="https://cloud.githubusercontent.com/assets/8245107/18581373/8f48c238-7c00-11e6-9416-1910d0729147.png">

**I can definitely implement it - what do you think of this suggestion?**

**Comment by skafandri** [comment]
What do you mean by "transaction name"

**Comment by skafandri** [comment]
If you are referring to the command name, the correct way to do it is to extend ConsumerCommand and override `getName()`

**Comment by JonasHaouzi** [comment]
In NewRelic, there is [a concept of transaction](https://docs.newrelic.com/docs/apm/transactions) name. Basically, any script launched on the system is a transaction. You can then select any of them and analyse its performances (queries, calls, etc..).

If the developer doesn't define the name of the transaction, NewRelic will try to define one automatically. 

Two examples:

1. A user coming on the website that calls PHP will create a new transaction. By default, the transaction name is going to be the URL
2. A developer launch a command in CLI. By default, the transaction name is going to be the command name.

The idea here is to set this name automatically, based on the consumer name.

**Comment by skafandri** [comment]
I don't think the bundle should alter the command name based on another bundle. What happens to other processes expecting that command name. For example, I use supervisor to run my consumers. I think the relic bundle you are using should offer a mechanism to hook into the transaction name (config, tag..) I cannot say because I never used it.

**Comment by skafandri** [comment]
It seems that the relic bundle indeed offers a mechanism to hook into the naming strategy https://github.com/ekino/EkinoNewRelicBundle/blob/master/README.md#transaction-naming-strategies

**Comment by alexbumbacea** [comment]
It would be even nicer if each message would be a stand alone transaction.
If you also include the time waiting for messages in the timings, you might get some random numbers.

**Comment by JonasHaouzi** [comment]
@alexbumbacea Indeed, you're right, after a couple of weeks of using, that's what we're going to do in our project. Each message has to be an single transaction we could follow through NR interface. That would make us able to spot the exceptions, the slow messages, etc...

@skafandri Something I agree with is that theoretically this bundle **should not** be coupled to the NewRelic implementation. However, most of the developers share the same needs (as we and @alexbumbacea) which makes this feature really worthwhile for this project. One more time, we'll do it for our needs but I'm willing to fork the project and submit a PR if you agree on the principle.

**Comment by alexbumbacea** [comment]
RabbitMQ bundle support listeners now. We have implemented this on our end with a service like this:

```
class NewRelicQueue implements EventSubscriberInterface
{

    /**
     * @var NewRelicInteractorInterface
     */
    protected $newRelicInteractor;

    /** @var  NewRelic */
    protected $newrelic;

    public function setNewRelicInteractor(NewRelicInteractorInterface $newRelicInteractor)
    {
        $this->newRelicInteractor = $newRelicInteractor;
    }

    public function setNewRelic(NewRelic $newRelic)
    {
        $this->newrelic = $newRelic;
    }

    /**
     * @inheritdoc
     */
    public static function getSubscribedEvents()
    {
        return [
            BeforeProcessingMessageEvent::NAME => 'onStart',
            AfterProcessingMessageEvent::NAME  => 'onStop',
        ];
    }

    public function onStart(AMQPEvent $event)
    {
        //ignore start transaction from consumer
        $this->newRelicInteractor->ignoreTransaction();
        //only for free new relic

        $this->newRelicInteractor->startTransaction($this->newrelic->getName());
        $this->newRelicInteractor->disableBackgroundJob();
        $this->newRelicInteractor->setTransactionName(
            'consumer_' . $event->getAMQPMessage()->delivery_info['exchange']
        );
    }

    public function onStop(AMQPEvent $event)
    {
        $this->newRelicInteractor->endTransaction();
    }
}
```

**Comment by skafandri** [comment]
Very good example from @alexbumbacea can be the start of a **how to** section in the documentation,
