### ISSUE TITLE
Command purge : InvalidArgumentException

### ISSUE THREAD

**Issue by guiyomh** [php-amqplib/RabbitMqBundle#389]
Hi, 

I have found a this exception :

![image](https://cloud.githubusercontent.com/assets/363162/19080008/efd894e4-8a55-11e6-8f9e-14c5bfe7bcdc.png)

**Comment by skafandri** [comment]
can you provide more details?  
-  bundle version
-  symfony version

**Comment by keksa** [comment]
Hello @skafandri, this just happened to me as well.
As I'm using Symfony 3.2, the "dialog" helper is no longer there (see http://symfony.com/doc/current/components/console/helpers/dialoghelper.html).
PR #346 solves this, any chance it could be merged?
