### ISSUE TITLE
PHP Error due to bracket in PHP 5.3

### ISSUE THREAD

**Issue by ariault-blanchard** [php-amqplib/RabbitMqBundle#391]
Hi,

While i was using composer to get this bundle, i've seen an error during the process : 

```
13:31:36  ** [out :: 10.34.149.24] PHP Parse error:  syntax error, unexpected '[' in /docs/releases/20161005132929/vendor/php-amqplib/rabbitmq-bundle/DependencyInjection/Compiler/InjectEventDispatcherPass.php on line 33
```

The problem is that there is bracket instead of curly bracket in this file : `RabbitMqBundle/DependencyInjection/Compiler/InjectEventDispatcherPass.php`.

So if you are on PHP 5.3, it'll throw a parse error.

```
    $definition->addMethodCall(
        'setEventDispatcher',
        [
            new Reference(self::EVENT_DISPATCHER_SERVICE_ID, ContainerInterface::IGNORE_ON_INVALID_REFERENCE)
        ]
    );
```

To make it compatible with PHP 5.3, it should be : 

```
    $definition->addMethodCall(
        'setEventDispatcher',
        array(
            new Reference(self::EVENT_DISPATCHER_SERVICE_ID, ContainerInterface::IGNORE_ON_INVALID_REFERENCE)
        )
    );
```

Regards.

AB.

**Comment by skafandri** [comment]
This was already fixed in master. I will release the fix version by tomorrow.

**Comment by ariault-blanchard** [comment]
Thx :)

**Comment by ariault-blanchard** [comment]
Hi, it seems that your changes are not available in packagist.

Can you push it ?

Regards.

AB.

**Comment by skafandri** [comment]
https://packagist.org/packages/php-amqplib/rabbitmq-bundle#v1.11.1
