### ISSUE TITLE
Priority Queues

### ISSUE THREAD

**Issue by aequasi** [php-amqplib/RabbitMqBundle#394]
Now that RabbitMQ [supports priority queues](https://www.rabbitmq.com/priority.html), can we get some documentation on it?

There was an issue from 2013 (#122), but rabbit didnt have priority queues then.

**Comment by makasim** [comment]
This will be done if PR https://github.com/php-amqplib/RabbitMqBundle/pull/516 is merged.

**Comment by MohamedHuzien** [comment]
@aequasi  @makasim  check this PR [#558](https://github.com/php-amqplib/RabbitMqBundle/pull/558)

**Comment by mkingbe** [comment]
@makasim any news ?
