### ISSUE TITLE
[Feature] Bulk Consumer

### ISSUE THREAD

**Issue by tiborb** [php-amqplib/RabbitMqBundle#403]
I suggest the implementation of a bulk consumer. 
It would load a batch of message from RabbitMQ, and ack them all at once when the task is complete.
The batch size and timeout would be configurable.

Example usage for bulk loading data into a database.
Further reading: http://www.rabbitmq.com/consumer-prefetch.html

Any thoughts?

-Tibor

**Comment by skafandri** [comment]
using the prefetch feature, prefetch_count messages will be loaded in your process memory. Then acked/nacked one by one. So the "batch" loading behavior is already implemented.
Is the batch acking/nacking worth the effort?

**Comment by tiborb** [comment]
Inserting multiple values (bulk) into a database, e.g column store, and ack onfy if the db insert was sucessful.

**Comment by devrck** [comment]
I would like to give it a shoot, because funny enough we implemented something similar :laughing:

**Comment by tiborb** [comment]
Awesome, would like to hear about your implementation :+1:

**Comment by devrck** [comment]
When you guys have the time please review my initial PR.
