### ISSUE TITLE
[Question] Multiple consumers limits

### ISSUE THREAD

**Issue by tiborb** [php-amqplib/RabbitMqBundle#407]
Hello folks,

I have the issue that i have one queue per user and want to keep the number of consumers down as the users are getting more and more over time.

I would give it a try with hundreads of queues per consumer.
What is the largest number of queues per (multiple) consumer you have ever used?

**Comment by skafandri** [comment]
The maximum I had on production was a bit less than 30k queues. It will depend mostly on your setup (hardware+configuration). Keep in mind that:
more queues and less consumers => more memory footprint in rabbitmq servers  
less queues and more consumers => mode memory footprint in your application servers

Needless to compare PHP and Erlang, tune to your own needs.
