### ISSUE TITLE
Get an event after a queue processing all messages.

### ISSUE THREAD

**Issue by Brah0um** [php-amqplib/RabbitMqBundle#408]
Hi,

I want to know if there is a way to get an event after my queue processing all messages ?

Currently, I can only get the event _'after_processing'_. I need this because I want to add a notification after processing all messages.

Thank you for your reply,

**Comment by skafandri** [comment]
You can subscribe to `console.terminate` event. You will get a `Symfony\Component\Console\Event\ConsoleCommandEvent` containing a `OldSound\RabbitMqBundle\Command\BaseRabbitMqCommand` object along with the `input` and `output`

**Comment by Brah0um** [comment]
Thanks @skafandri :)
