### ISSUE TITLE
Rejecting messages after a couple of of attempts

### ISSUE THREAD

**Issue by JonasHaouzi** [php-amqplib/RabbitMqBundle#421]
### Preamble
AFAIK, this bundle doesn't provide any system of "maximum retry" for messages. [RabbitMQ neither](http://stackoverflow.com/questions/23158310/how-do-i-set-a-number-of-retry-attempts-in-rabbitmq).
The DLX doesn't fully cover this needs cause it will simply try to reparse the message over and over as discussed in #328. We need this system for our system and we're going to implement it.

### Our implementation
Our idea is to provide a new custom attribute as suggested [in here](http://stackoverflow.com/questions/23158310/how-do-i-set-a-number-of-retry-attempts-in-rabbitmq) that will be a simple counter of the number of times a given message have been parsed. This number will be incremented through `\OldSound\RabbitMqBundle\RabbitMq\Consumer` (in order to be as transparent as possible for the developer).

Using this counter value, the developer is able to stop consuming this message and `REJECT` it when he's assuming to many attempts have been made (letting the developer taking care of that allows him saving this message into a database (or any other storage system) to review later why it has fails).

**We're currently working on this implementation locally and we could publish our code once done.**

Could you give us your opinion?

Thanks :-)

**Comment by skafandri** [comment]
The concept seems interesting. Right now stackoverflow is down so I couldn't check the links :)
Can you give a real life scenario (maybe describe your own) and how it would benefit from this feature.

**Comment by JonasHaouzi** [comment]
**Definitely, here is an example.**

Some of our messages require a database to run correctly, but in some extreme cases, this database is simply unavailable or too busy to reply. When this happens, the messages goes to a `DLX` and is getting parsed again a couple of minutes later.

At the second parsing, let's say that the database is available, so the process keep going. While running the job this message asks to, we realise this message can't be correctly processed (arbitrary reason).

**Well, we have two choices:**
1. Keep sending this message to a `DLX` and it will be parsed over and over,
2. Or, assume that we can't parse this message, taking it off the queue, and warn the developer that a message can't be handled.

In that case, this is the current workflow:
```
1. The message is read... database is not available ➝ message sent into a DLX
2. The message is parsed again after 1 minute... database still not available ➝ retry later
3. The message is parsed again after 1 minute... database IS available, but can't be properly handled (let's say this message execute a SQL query that the server fails to run at this time) ➝ retry later
4. And the process will be repeated again, and again...
```

We this counter, we could do (only the step `4.` is different): 
```
1. The message is read... database is not available ➝ message sent into a DLX
2. The message is parsed again after 1 minute... database still not available ➝ retry later
3. The message is parsed again after 1 minute... database IS available, but can't be properly handled (let's say this message execute a SQL query that the server fails to run at this time) ➝ retry later
4. The message is parsed again after 1 minute... is fails, and we realise it's the third time we try to process it. In our case, we will define that this is the MAXIMUM attempt we allow. We will REJECT this message, and warn the technical team.
```

I hope this is clear enough!

Thanks.

**Comment by JonasHaouzi** [comment]
@felixcarpena pointed out that the `DLX` provides a counter as described in https://felipeelias.github.io/rabbitmq/2016/02/22/rabbitmq-exponential-backoff.html (through the `x-death` header).

This behaviour doesn't work great for us, we can't get this header... I let this discussion open waiting for more feedbacks.

**Comment by skafandri** [comment]
I see your case. This a very common situation that we deal with daily. The problem with your setup that led you to think about a maximum retries is that you don't have a separation between a temporary failure and a permanent one. If you use an arbitrary number N to decide wether to retry a message or not, you will inevitably fall into one of the situations:
- N is too big and you keep retrying a message N times while it could have been discarded from the first try.
- N is not big enough and you discard a message at N that could have been successfully processed at N+1 

This is how I deal with this situation.
- On temporary failure (database down, timeout, a rat ate the cable...), reject the message
- On permanent failure (image too big to process, wrong email receipient, order id already processed...) ack the message. And in some situations published to another queue for special handling.

**Comment by Ard-Jan** [comment]
This is exactly what we need. Any idea when this will be released?

**Comment by podorozhny** [comment]
+1

**Comment by Nguimjeu** [comment]
@JonasHaouzi 

> @felixcarpena pointed out that the DLX provides a counter as described in https://felipeelias.github.io/rabbitmq/2016/02/22/rabbitmq-exponential-backoff.html (through the x-death header).
> 
> This behaviour doesn't work great for us, we can't get this header... I let this discussion open waiting for more feedbacks.

Is there any reason why can't you get the headers? So far I know, you can access headers data with something like this:

```php
/** @var AMQPMessage $queueMessage */
$props = $queueMessage->get_properties();
/** @var AMQPTable $applicationHeaders */
$applicationHeaders = $props['application_headers'];
$xdeath = !isset($applicationHeaders->getNativeData()['x-death']) ?: $applicationHeaders->getNativeData()['x-death'];
$count = $xdeath ? $xdeath[0]['count'] : 0;
```

And then use the count value to remove the message from the `main` queue by `ACK-ing` it

Something like:

```php
if ( $count > self::MAX_ATTEMPTS) {
    $channel->basic_ack($queueMessage->delivery_info['delivery_tag']);
}
```

Correct me if I'm wrong

**Comment by choonge** [comment]
Sounds like a great feature, would love this. Would be especially great if retry-delays and max-tries could be configurable per consumer.

**Comment by VincentLanglet** [comment]
I just had an infinite loop because RabbitMQ requeued every time.

This feature would be great. Are you working on it @JonasHaouzi ?

**Comment by mihaileu** [comment]
Any news here ?

**Comment by Gyvastis** [comment]
> @JonasHaouzi
> 
> > @felixcarpena pointed out that the DLX provides a counter as described in https://felipeelias.github.io/rabbitmq/2016/02/22/rabbitmq-exponential-backoff.html (through the x-death header).
> > This behaviour doesn't work great for us, we can't get this header... I let this discussion open waiting for more feedbacks.
> 
> Is there any reason why can't you get the headers? So far I know, you can access headers data with something like this:
> 
> ```
> /** @var AMQPMessage $queueMessage */
> $props = $queueMessage->get_properties();
> /** @var AMQPTable $applicationHeaders */
> $applicationHeaders = $props['application_headers'];
> $xdeath = !isset($applicationHeaders->getNativeData()['x-death']) ?: $applicationHeaders->getNativeData()['x-death'];
> $count = $xdeath ? $xdeath[0]['count'] : 0;
> ```
> 
> And then use the count value to remove the message from the `main` queue by `ACK-ing` it
> 
> Something like:
> 
> ```
> if ( $count > self::MAX_ATTEMPTS) {
>     $channel->basic_ack($queueMessage->delivery_info['delivery_tag']);
> }
> ```
> 
> Correct me if I'm wrong

Thanks for the example! It would be great as a bundle feature though.
