### ISSUE TITLE
Is it possible to use this bundle without symfony app framework? or decouple?

### ISSUE THREAD

**Issue by zspine** [php-amqplib/RabbitMqBundle#422]
RabbitMqBundle's  is based on Thumper and it seems Thumper library no longer maintained. So am just wondering whether it is possible to use this bundle in a custom framework based php application? I have checked the code and it seems possible, but am not sure whether it's a good idea to do this on a production app.

https://github.com/php-amqplib/RabbitMqBundle/tree/master/RabbitMq
(not coupled with any symfony app related stuff)

Or is it a good idea to fork and decouple it as a separate php component?

**Comment by skafandri** [comment]
RabbitMqBundle is not based on Thumper, it depends on [php-amqplib](https://github.com/php-amqplib/php-amqplib) which is maintained.
You can use php-amqplib in any PHP project, if however you want to use RabbitMqBundle alone, you would need symfony/console (to run consumers) and optionally symfony/event-dispatcher and monolog/monolog.

If you need any help to port it to any PHP framework, or support to use it in a stand alone project I can help.

**Comment by zspine** [comment]
@skafandri Thanks for the quick response and generous support :). Now it make sense.. 

We are already using php-amqplib, but it's not convenient as Thumper or RabbitMqBundle. RabbitMqBundle uses better oop structure and patterns and easy to extend, this is the only reason we are looking for an existing library before we develop our own on top of php-amqplib.

Yes, am planning the possibility of decoupling the rabbit-mq part of the bundle from symfony app dependency (symfony component dependency is not an issue and it can remain as is). Sylius project doing a great job with decoupling common and framework related dependency. So the common php component can be used to implement with any framework or standalone.

http://docs.sylius.org/en/latest/components/Addressing/index.html
http://docs.sylius.org/en/latest/bundles/SyliusAddressingBundle/index.html

> If you need any help to port it to any PHP framework, or support to use it in a stand alone project I can help.

Thanks again, sure will try to decouple and implement it as a standalone php component. will contact you if I need any help.... (cheers)

**Comment by skafandri** [comment]
Technically, it is almost enough to extract [RabbitMq](https://github.com/php-amqplib/RabbitMqBundle/tree/master/RabbitMq) folder as a library. Most of the code depends only on PhpAmqpLib. Here is an example without Symfony (or any other dependencies)

````
<?php
use OldSound\RabbitMqBundle\RabbitMq\Consumer;
use PhpAmqpLib\Connection\AMQPStreamConnection;
use PhpAmqpLib\Message\AMQPMessage;

require __DIR__ . '/../vendor/autoload.php';

$consumer = new Consumer(new AMQPStreamConnection('localhost', 5672, 'rabbitmq', 'rabbitmq'));
$consumer->setQueueOptions(['name' => 'test']);
$consumer->setExchangeOptions(['name' => 'test', 'type' => 'fanout']);
$consumer->setCallback(function (AMQPMessage $message) {
    echo $message->getBody();
    return true;
});
$consumer->consume(1);
````

**Comment by zspine** [comment]
@skafandri That is exactly we are trying to achieve, Thanks a lot for the input and quick response! really very helpful!!! will give it a try and will let you know how it goes!

**Comment by skafandri** [comment]
Just curious, are you actually going to use rabbitmq with Sylius or it was just an example?

**Comment by zspine** [comment]
@skafandri sorry just noticed your message! it was just an example!

**Comment by zspine** [comment]
@skafandri it worked like a charm :) , I just had to remove the symfony event dependencies... I also used https://github.com/swarrot/swarrot library to consumer messages.

Thank you for your guidance and help

**Comment by skafandri** [comment]
@zspine good to hear that :)
