### ISSUE TITLE
Producers Not Declaring Queue

### ISSUE THREAD

**Issue by ktischer** [php-amqplib/RabbitMqBundle#43]
Great work on this, it has saved us tons of time.

One thing however...  In my somewhat brief exposure to the AMQP world, I find it is usually recommended to create your exchange and queues on the sending as well as the receiving side.  This prevents messages from never reaching the exchange/queue due to it being deleted etc...  

We are pushing into a queue that is talking to a log server.  The server will create the queue, but it would be good if that server were to go down and the queue was to somehow get deleted, we could have assurance that it would recreate and continue sending.

We are working on a pull for this but wanted to find out if there was a rationale behind it.

**Comment by ramunasd** [comment]
So You can declare queue as durable and it won't disappear 🤷 
As I see some changes were made, so i'm closing this.
