### ISSUE TITLE
[Question] Multiple consumer for single queue

### ISSUE THREAD

**Issue by haegemon** [php-amqplib/RabbitMqBundle#431]
I want start multiple consumers for a single queue. But a  consumer picks up all message from the queue. A single consumer work and others do nothing. Is it possible to set consumer get a single message from queue, then proceed it, than get another message and etc?

**Comment by skafandri** [comment]
yes, use the **prefetch_count** config to specify how many messages a consumer is allowed to get at once

**Comment by haegemon** [comment]
Yes, that great.Thanks.
