### ISSUE TITLE
Consummer command 

### ISSUE THREAD

**Issue by themayna** [php-amqplib/RabbitMqBundle#432]
Hi there,
i have been using this bundle for a wile and it's just awesome...but my app is getting bigger with more then 5 consumers & produces and i find it had to keep track of them...
Is it possible to have a command with a description and a function that receives the message for every consumer? i think it would be a lot usefull if we have something like:
rabbitmq:consumer.consume_sites  descripntion bla bla bla
rabbitmq:consumer.consume_pages description bla bla bla
rabbitmq:consumer.consume_bla_bla bla bla bla

Is there i have mai execute function in a command instead of a service?so i can call the service logic from that command?
Thanks.

**Comment by skafandri** [comment]
With MultipleConsumer you can consume multiple queues with a single consumer.
Can you provide an example to explain how you expect to **execute a function in a command**.
5 consumers is not that big, I saw applications with 200+ consumers.

**Comment by themayna** [comment]
hi there,
i would like to have a custom command for every consumer(add description and if possible, custom parameters) so it will be easyer to manage them with supervisor. i will like to recieve the $msg->body mesaage in the command class so i can then process it. if i have 50 consumers it will be hard to remember the rabbitmq:message parameter.
thanks

**Comment by themayna** [comment]
<?php

namespace AppBundle\Command;

use PhpAmqpLib\Message\AMQPMessage;
use Symfony\Component\Console\Input\InputInterface;
use Symfony\Component\Console\Output\OutputInterface;

/**
 * Class SiteConsumerCommand
 * @package AppBundle\Command
 */
class SiteConsumerCommand extends BaseConsumerCommand

{
    function configure()
    {
        $this->setName('rabbitmq:consumer:sites');
    }


    function execute(InputInterface $input, OutputInterface $output)
    {
        return parent::execute($input, $output); // TODO: Change the autogenerated stub
    }

    public function processMessageCallback(AMQPMessage $msg)
    {
        //do something witht the $msg here
    }
}

**Comment by themayna** [comment]
something like this? without having to have the 
`    public function execute(AMQPMessage $msg)
    {
    }`
in a prefined service

**Comment by agentsib** [comment]
May be this help...

http://symfony.com/doc/current/console/calling_commands.html

**Comment by themayna** [comment]
uhm, this is nicer than the solution i found...i will refactor my code, thanks a lot
