### ISSUE TITLE
[Question] Scaling with multiple consumers ?

### ISSUE THREAD

**Issue by xhuberdeau** [php-amqplib/RabbitMqBundle#437]
Hello, thanks for this awesome bundle.

I have a question about scaling: running heavy jobs (counting in minutes), I ran 10 consumers. I expected my job to be 10x faster than with only 1 consumer. But in fact, each consumer receive less messages. It is to say whether I have 1 or 10 consumers, the execution time doesn't change. I configured the qos to ensure the messages are fairly dispatched (it's working well, each consumer has the same amount of messages).

Is this normal ? Thank you.

**Comment by skafandri** [comment]
Do you have enough messages to *feed* all consumers, that is: available messages > prefetch_count X number of consumers?

**Comment by xhuberdeau** [comment]
Well, yes. I have a prefetch_count of 10, for 7800 messages. So in theory, that should allow me to have 780 consumers, and to finish the task like if there were only 10 messages.

**Comment by skafandri** [comment]
Then are your consumers competing for a shared resource like a database, or hardware like CPU?

**Comment by xhuberdeau** [comment]
Yes, they persist data into a DB.

**Comment by skafandri** [comment]
Usually performance scales almost linearly when you start adding consumers, depending on your message broker hardware and configuration, and your application's hardware.

What you described seems odd, I am doubting you have a race condition somewhere.

Can you share your consumer code and the relevant parts of your code that is being called?

If you can provide a situation we can reproduce, most probably we can help you.

**Comment by xhuberdeau** [comment]
So I did one simple test you can reproduce easily: I made a for loop from 0 to 9999 in which I publish the loop index 
`for ($i = 0; $i < 10000; $i++) {
     $this->producer->publish(base64_encode(serialize(array("val" => $i))));
}`
and my consumer is only responsible for logging the index of the loop:
`$data = unserialize(base64_decode($msg->body));
 $this->logger->info(sprintf('val : %s', $data['val']));
 return;` 
It took 1min03s to display from 0 to 9999 for one consumer. It took 55 sec for 10 consumers.
So it's nothing big, the CPU, RAM and disk usage remained almost the same.
Any thought ?

**Comment by skafandri** [comment]
Interesting, can you share also?

- your consumer configuration
- how you are running the consumer commands

**Comment by xhuberdeau** [comment]
Here is the configuration:
`
old_sound_rabbit_mq:
    connections:
        default:
            host:     'localhost'
            port:     5672
            user:     'guest'
            password: 'guest'
            vhost:    '/'
            connection_timeout: 3
            read_write_timeout: 3
            keepalive: false
            heartbeat: 0
    producers:
        myProducer:
            connection:       default
            exchange_options: {name: 'myProducer', type: direct}
consumers:
        myProducer:
            connection:       default
            exchange_options: {name: 'myProducer', type: direct}
            queue_options:    {name: 'myProducer'}
            callback:         my_producer_consumer
            qos_options:      {prefetch_size: 0, prefetch_count: 10, global: false}
`
(I renamed the name of the producer on purpose).

Here is how I run my consumers:
`
php app/console rabbitmq:consumer myProducer -vv --env=prod
`

**Comment by skafandri** [comment]
Can you also share how you run 10 consumers

**Comment by xhuberdeau** [comment]
For 10 consumers, I run 10 consoles with the command I provided in my previous message.
