### ISSUE TITLE
Command for listing defined consumers and producers

### ISSUE THREAD

**Issue by needle-project** [php-amqplib/RabbitMqBundle#442]
Currently I'm not aware of any method of listing the consumers and producers from my application.

A command with listing consumers and producers will be a great asset in usability, especially when dealing with application with a large number of consumers/producers and reading the configuration file may not be that comfortable to navigate in.

Is there a form (other than scrolling through the configuration file) to obtain the defined consumers and producers?

**Comment by skafandri** [comment]
List all consumers:
````
app|bin/console debug:container|grep old_sound_rabbit_mq.*_consumer
````
List all producers
````
app|bin/console debug:container|grep old_sound_rabbit_mq.*_producer
````

**Comment by needle-project** [comment]
I think we both can agree that is not an elegant method.

Would you consider a new development to handle this feature?

Please revise https://github.com/php-amqplib/RabbitMqBundle/compare/master...needle-project:ISSUE-442

**Comment by skafandri** [comment]
Can you explain the advantage of a new command?  
My suggested commands does not do the job?

**Comment by needle-project** [comment]
Yes, it does... But it think it is more of the bundle responsibility to expose these resources, not by debugging the container. It is just a feature to improve usage.

Your method also does the job but how "handy" is to for regular users?

**Comment by skafandri** [comment]
The bundle responsibility is to integrate with Symfony framework and use it's mechanisms whenever possible.

I think is better for regular users to use the same mechanisms they are already accustomed to,

````
#List all loggers (MonologBundle)
app/console debug:container  --tag monolog.logger

#List all event listeners (FrameworkBundle)
app/console debug:container  --tag kernel.event_listener

#List all normalizers (FosRestBundle)
app/console debug:container  --tag serializer.normalizer

#List all twig extensions (TwigBundle)
app/console debug:container  --tag twig.extension
````
It follows naturally
````
#List all consumers (RabbitMqBundle)
app/console debug:container --tag=old_sound_rabbit_mq.consumer
````

**Comment by needle-project** [comment]
Thank you for your response.

I fully understand and respect your point of view, even if I still think that a more specific tool can be of help.

In the scenario given with a new user, app|bin/console it is the first "entry-point", without the necessity of fully understanding how Consumers and Producers services are built (using service tags) so further using tag listing and just start from "rabbitmq" namespace from console.

But again, I respect your decision.

Thank you,
Adrian
