### ISSUE TITLE
Not working on symfony 2.3

### ISSUE THREAD

**Issue by alinalexandru** [php-amqplib/RabbitMqBundle#444]
I am trying to fix this issue. You have requested a non-existent service "old_sound_rabbit_mq.connection_factory.*"
The problem is on setting the factory service on symfony 2.3

Until now I have updated the .travis file to reproduce the problem.
https://github.com/alinalexandru/RabbitMqBundle/tree/fix-factory-sf2.3

A solution can be to make public the factory service (DependencyInjection/OldSoundRabbitMqExtension.php line 84) or to use setFactoryClass (to instantiate private factory)

Any help would be appreciated

**Comment by mvrhov** [comment]
Just downgrade the bundle. Sf 2.3 is unsupported AFIR.

**Comment by stloyd** [comment]
TBH. I would prefer to officially drop "support" for Symfony 2.3 as it's not maintained almost year & in next month it also loses security support, than fixing the code to match this outdated version.

**Comment by alinalexandru** [comment]
I totally agree with you.
For me at that old project was much easy to fix this issue than upgrading symfony.

**Comment by muhammadtaqi** [comment]
@stloyd I'm using it with `"symfony/symfony": "2.3.18"` with `"php-amqplib/rabbitmq-bundle": "~1.7"` and got same error. Please confirm what minimum symfony version is required ?
