### ISSUE TITLE
TLS support - Client connection

### ISSUE THREAD

**Issue by PGBastien** [php-amqplib/RabbitMqBundle#448]
It would be relevant add the feature for client ssl connection, the **php-amqplib** provided **AMQPSSLConnection.php**.

What do you think ?

**Comment by PGBastien** [comment]
TLS support is OK 👍 

config.yml 
port : 5673 (rabbitmq.config)
ssl_context:
                key: 'path/to/cacert.pem'

**Comment by lemonlab** [comment]
+1

**Comment by PGBastien** [comment]
Hi @lemonlab,
You can support ssl in your client connection.

**Prior**
Enable TLS listeners in Rabbit
See https://www.rabbitmq.com/ssl.html


**And add this params in your connection :** 
_config.yml_

```
client_ssl_connection :
[...]
     port:     5673
     vhost:    'vh-client12345'
     ssl_context:
          verify_peer: true
[...]
```

**And define your CA cert file in your web server**

**Comment by lemonlab** [comment]
Perfect ! Thank you :)
