### ISSUE TITLE
New 1.12.x tag?

### ISSUE THREAD

**Issue by acasademont** [php-amqplib/RabbitMqBundle#450]
Hi!

Right now the MultipleConsumer is missing commit https://github.com/php-amqplib/RabbitMqBundle/commit/20c2f4a28394131907a976823f9d0498ef62ae4b which actually fixed a bug. Would it be please possible to tag a new bug release for that one? We can't really stop multiple consumers using signals at this point. Thanks!!

**Comment by stloyd** [comment]
Just release `1.13.0`! https://github.com/php-amqplib/RabbitMqBundle/releases/tag/v1.13.0

**Comment by acasademont** [comment]
Thx @stloyd much appreciated!
