### ISSUE TITLE
Issue with memory limit

### ISSUE THREAD

**Issue by kufd** [php-amqplib/RabbitMqBundle#453]
Hi 
I have found an issue with memory limit in the latest release 1.13.0

1) In file RabbitMq/Consumer.php line 215
There are confused parameters in method MemoryConsumptionChecker::isRamAlmostOverloaded
Now is  $memoryManager->isRamAlmostOverloaded($this->getMemoryLimit(), '5M');
But should be $memoryManager->isRamAlmostOverloaded('5M', $this->getMemoryLimit());

2)There is an issue with conversion parameter **memory limit** for consumer command
As example if to pass parameter -l 128  than method MemoryConsumptionChecker::convertHumanUnitToNumerical converts it into 128 bytes
But if to pass parameter -l 128M than validation in BaseConsumerCommand::initConsumer will be failed
Also documentation says that memory limit parameters is in megabytes

**Comment by notrix** [comment]
:+1: 

This is major BC break!

**Comment by enleur** [comment]
Have the same issue after update

**Comment by kufd** [comment]
This problem was fixed in master 6 month ago
https://github.com/kufd/RabbitMqBundle/commit/068020d115379baea501667931501c65dd6e6cf9

But unfortunately it is present in latest release
And it breaks applications

**Comment by ArthurJam** [comment]
+1

**Comment by enleur** [comment]
Any plans on 1.14 release?

**Comment by ramunasd** [comment]
As I see it was fixed. Command line accepts only integers and always interprets them as megabytes(2^20).
