### ISSUE TITLE
"graceful_max_execution" option for rpc server?

### ISSUE THREAD

**Issue by maximivanov** [php-amqplib/RabbitMqBundle#457]
I guess long running rpc server suffers from the same problems as consumers (memory exhaustion, loosing connection to servers). Does it make sense to add `graceful_max_execution` option to rpc server config also?

**Comment by acasademont** [comment]
@maximivanov I think it does, same for multiple or dynamic consumers

**Comment by easy-dev** [comment]
Another issue is that both of them doesn't support signals handling.
