### ISSUE TITLE
Single consumer for multiple queues?

### ISSUE THREAD

**Issue by enumag** [php-amqplib/RabbitMqBundle#465]
I'd like to have a one consumer that would consume messages from multiple queues. Is this possible? In the configuration found in the docs I only found examples with single queue name for each consumer.

**Comment by oleg-andreyev** [comment]
Need to configure `queues` with all queues from what you want to consume messages

Ref.: https://github.com/php-amqplib/RabbitMqBundle/blob/master/README.md#multiple-consumers

```
multiple_consumers:
    upload:
        connection:       default
        exchange_options: {name: 'upload', type: direct}
        queues_provider: queues_provider_service
        queues:
            upload-picture:
                name:     upload_picture
                callback: upload_picture_service
                routing_keys:
                    - picture
            upload-video:
                name:     upload_video
                callback: upload_video_service
                routing_keys:
                    - video
            upload-stats:
                name:     upload_stats
                callback: upload_stats
```

**Comment by enumag** [comment]
@oleg-andreyev Thank you!

**Comment by enumag** [comment]
One more thing. If there are messages in several of the queues the MultiConsumer is connected to, what determines the order in which the messages will be processed by the consumer?

**Comment by oleg-andreyev** [comment]
@enumag it is something what isn't related to bundle. In short: RabbitMQ guarantees order of processing with a single queue, with multiple queues involved there are no guarantees.

Ref.: https://stackoverflow.com/a/21363518/1205171

**Comment by enumag** [comment]
@oleg-andreyev That stackoverflow answer is not related to my question - it is about single queue with multiple consumers. My question is about multiple queues with single consumer which is completely different.

**Comment by oleg-andreyev** [comment]
@enumag I'm 90% sure it's has same behavior. Don't get me wrong, but it's not a support ticket for Rabbit ;)

**Comment by enumag** [comment]
@oleg-andreyev Yeah, I thought that would be the case. Is there a way to somehow prioritize which queues should be consumed first? It does not have to be reliable, just something that would raise the probability.

**Comment by oleg-andreyev** [comment]
@enumag can't answer that, but you probably could use priorities
https://www.rabbitmq.com/priority.html
https://www.rabbitmq.com/consumer-priority.html
