### ISSUE TITLE
BC brake

### ISSUE THREAD

**Issue by chernecov** [php-amqplib/RabbitMqBundle#467]
https://github.com/php-amqplib/RabbitMqBundle/commit/0d35a82506f03499d03a186a3f40bc49216f56b6
This commit breaks all overrides of **MultipleConsumerCommand*.
Problem is in arguments sequence.

https://github.com/php-amqplib/RabbitMqBundle/blob/master/Provider/QueuesProviderInterface.php
This interface should be changed to require context as well as this possibility should be reflected in bundle's description.

**Comment by oleg-andreyev** [comment]
@chernecov what is exactly broken, any example for maintainers, and probably we could prepare PR, if it's really broken
