### ISSUE TITLE
Travis broken

### ISSUE THREAD

**Issue by tiborb** [php-amqplib/RabbitMqBundle#469]
Builds are broken for php 5.3 becasue the php version is not available in the build enviorment.

**Comment by skafandri** [comment]
@tiborb I think is time to bump up PHP version and release a major version, what do you think?

**Comment by ibrahimgunduz34** [comment]
Make sense. I just want to make works. I think 5.4 and 5.5 may removable also, because of even php give support min. 5.6 until dec 2018. Does it make sense ?

**Comment by skafandri** [comment]
I think supporting active versions is the least we can do, so 5.6 seems OK for me.

**Comment by ramunasd** [comment]
We migrated to github actions.
