### ISSUE TITLE
Accessing channel objects as a service when it needed.

### ISSUE THREAD

**Issue by ibrahimgunduz34** [php-amqplib/RabbitMqBundle#471]
Sometimes we need to access AMQPChannel objecs as a service, when we need to send messages from application to RabbitMQ through some third party libraries which requires a channel instance as dependency.

My case is about sending application logs from my application to graylog over rabbitmq using monolog. Monolog expects an instance of AMQPChannel or AMQPExchane as a dependency to AmqpHandler.

**Comment by skafandri** [comment]
If I understand correctly, you want to register Channels as services. I PR is welcome.
