### ISSUE TITLE
Using graceful_max_execution + signals causes RabbitMQ errrors

### ISSUE THREAD

**Issue by acasademont** [php-amqplib/RabbitMqBundle#473]
We've been trying the graceful_max_execution feature but wen we send the SIGTERM signal to one of the consumers it stops with an exception

  [PhpAmqpLib\Exception\AMQPIOWaitException]
  A network error occured while awaiting for incoming data

and also in the RabbitMQ server logs we can see this line

=ERROR REPORT==== 21-Sep-2017::17:26:12 ===
Error on AMQP connection <0.10742.516> (xxxx), channel 1:
operation basic.cancel caused a connection exception channel_error: "expected 'channel.open'"

It might be related to an issue described in php-amqplib/php-amqplib#458 where timeouts and signals do not play well together.

**Comment by acasademont** [comment]
Maybe that feature should be implemented without using the timeout features of the amqplib and instead relying on a simple time difference, much like the RAM or number of messages checks work. Thoughts?

**Comment by Soullivaneuh** [comment]
I have the same error using `idle_timeout` option:

```
sullivan@fbecbeaae646:/code$ ./bin/console rabbitmq:consumer analysis
^C
In AMQPReader.php line 128:
                                                            
  A network error occured while awaiting for incoming data  
                                                            

rabbitmq:consumer [-m|--messages [MESSAGES]] [-r|--route [ROUTE]] [-l|--memory-limit [MEMORY-LIMIT]] [-d|--debug] [-w|--without-signals] [-h|--help] [-q|--quiet] [-v|vv|vvv|--verbose] [-V|--version] [--ansi] [--no-ansi] [-n|--no-interaction] [-e|--env ENV] [--no-debug] [--] <command> <name>
```

Removing the option make the error disappearing.

**Comment by PabloScolpino** [comment]
I am experiencing the same error too. I'll hack a solution and make an ugly PR for this.

**Comment by piotrkochan** [comment]
> I am experiencing the same error too. I'll hack a solution and make an ugly PR for this.

any progress? :)

**Comment by PabloScolpino** [comment]
Well, as you might have guessed, no. I thought I had made a patch I never uploaded but after wrecking my brains a little while I remembered I left the related project before I could find a fix. It could be fun to try and fix this, I will make a note to cicle back to this in less than one year :sadtroll:

**Comment by ramunasd** [comment]
It was fixed on library side.
