### ISSUE TITLE
php-ampqlib v2.7.0 breaks RabbitMqBundle

### ISSUE THREAD

**Issue by larspohlmann** [php-amqplib/RabbitMqBundle#480]
Hi,

sadly I only have this part of the traceback, because we had to pin php-ampqlib to v2.6.2 quickly to keep our systems running. With php-ampqlib v2.6.2 this error doesn't occur.

Error 1:

QueuingService-Error: Error sending data. Last SocketError: Connection reset by peer in /var/www/contentmixer/releases/20171002122821/vendor/php-amqplib/php-amqplib/PhpAmqpLib/Wire/IO/SocketIO.php at line 165

--

/var/www/contentmixer/releases/20171002122821/vendor/stat/queuing-bundle/Stat/QueuingBundle/Services/QueuingService.php  in function «publish» on line: «315»
/var/www/contentmixer/releases/20171002122821/vendor/stat/content-bundle/Stat/ContentBundle/Services/QueueService.php  in function «sendMessage» on line: «66»
/var/www/contentmixer/releases/20171002122821/vendor/stat/content-bundle/Stat/ContentBundle/Consumer/RabbitmqPublishConsumer.php  in function «execute» on line: «50»
 in function «call_user_func»
/var/www/contentmixer/releases/20171002122821/vendor/php-amqplib/rabbitmq-bundle/RabbitMq/Consumer.php  in function «processMessageQueueCallback» on line: «88»
/var/www/contentmixer/releases/20171002122821/vendor/php-amqplib/rabbitmq-bundle/RabbitMq/Consumer.php  in function «processMessage» on line: «133»
 in function «call_user_func»
/var/www/contentmixer/releases/20171002122821/vendor/php-amqplib/php-amqplib/PhpAmqpLib/Channel/AMQPChannel.php  in function «basic_deliver» on line: «986»
 in function «call_user_func»
/var/www/contentmixer/releases/20171002122821/vendor/php-amqplib/php-amqplib/PhpAmqpLib/Channel/AbstractChannel.php  in function «dispatch» on line: «202»
/var/www/contentmixer/releases/20171002122821/vendor/php-amqplib/php-amqplib/PhpAmqpLib/Channel/AbstractChannel.php  in function «wait» on line: «340»
/var/www/contentmixer/releases/20171002122821/vendor/php-amqplib/rabbitmq-bundle/RabbitMq/Consumer.php  in function «consume» on line: «54»
/var/www/contentmixer/releases/20171002122821/vendor/php-amqplib/rabbitmq-bundle/Command/BaseConsumerCommand.php  in function «execute» on line: «90»
/var/www/contentmixer/releases/20171002122821/vendor/symfony/symfony/src/Symfony/Component/Console/Command/Command.php  in function «run» on line: «266»
/var/www/contentmixer/releases/20171002122821/vendor/symfony/symfony/src/Symfony/Component/Console/Application.php  in function «doRunCommand» on line: «874»
/var/www/contentmixer/releases/20171002122821/vendor/symfony/symfony/src/Symfony/Component/Console/Application.php  in function «doRun» on line: «203»
/var/www/contentmixer/releases/20171002122821/vendor/symfony/symfony/src/Symfony/Bundle/FrameworkBundle/Console/Application.php  in function «doRun» on line: «93»
/var/www/contentmixer/releases/20171002122821/vendor/symfony/symfony/src/Symfony/Component/Console/Application.php  in function «run» on line: «127»
/var/www/contentmixer/releases/20171002122821/app/console  in function «» on line: «22»

-----------------------

Error 2:

QueuingService-Error: Error reading data. Received 0 instead of expected 1 bytes in /var/www/contentmixer/releases/20171002122821/vendor/php-amqplib/php-amqplib/PhpAmqpLib/Wire/IO/SocketIO.php at line 131

--

/var/www/contentmixer/releases/20171002122821/vendor/stat/queuing-bundle/Stat/QueuingBundle/Services/QueuingService.php  in function «publish» on line: «315»
/var/www/contentmixer/releases/20171002122821/vendor/stat/content-bundle/Stat/ContentBundle/Services/QueueService.php  in function «sendMessage» on line: «66»
/var/www/contentmixer/releases/20171002122821/vendor/stat/content-bundle/Stat/ContentBundle/Consumer/RabbitmqPublishConsumer.php  in function «execute» on line: «50»
 in function «call_user_func»
/var/www/contentmixer/releases/20171002122821/vendor/php-amqplib/rabbitmq-bundle/RabbitMq/Consumer.php  in function «processMessageQueueCallback» on line: «88»
/var/www/contentmixer/releases/20171002122821/vendor/php-amqplib/rabbitmq-bundle/RabbitMq/Consumer.php  in function «processMessage» on line: «133»
 in function «call_user_func»
/var/www/contentmixer/releases/20171002122821/vendor/php-amqplib/php-amqplib/PhpAmqpLib/Channel/AMQPChannel.php  in function «basic_deliver» on line: «986»
 in function «call_user_func»
/var/www/contentmixer/releases/20171002122821/vendor/php-amqplib/php-amqplib/PhpAmqpLib/Channel/AbstractChannel.php  in function «dispatch» on line: «202»
/var/www/contentmixer/releases/20171002122821/vendor/php-amqplib/php-amqplib/PhpAmqpLib/Channel/AbstractChannel.php  in function «wait» on line: «340»
/var/www/contentmixer/releases/20171002122821/vendor/php-amqplib/rabbitmq-bundle/RabbitMq/Consumer.php  in function «consume» on line: «54»
/var/www/contentmixer/releases/20171002122821/vendor/php-amqplib/rabbitmq-bundle/Command/BaseConsumerCommand.php  in function «execute» on line: «90»
/var/www/contentmixer/releases/20171002122821/vendor/symfony/symfony/src/Symfony/Component/Console/Command/Command.php  in function «run» on line: «266»
/var/www/contentmixer/releases/20171002122821/vendor/symfony/symfony/src/Symfony/Component/Console/Application.php  in function «doRunCommand» on line: «874»
/var/www/contentmixer/releases/20171002122821/vendor/symfony/symfony/src/Symfony/Component/Console/Application.php  in function «doRun» on line: «203»
/var/www/contentmixer/releases/20171002122821/vendor/symfony/symfony/src/Symfony/Bundle/FrameworkBundle/Console/Application.php  in function «doRun» on line: «93»
/var/www/contentmixer/releases/20171002122821/vendor/symfony/symfony/src/Symfony/Component/Console/Application.php  in function «run» on line: «127»
/var/www/contentmixer/releases/20171002122821/app/console  in function «» on line: «22»

**Comment by OtezVikentiy** [comment]
+1 the same problem

**Comment by coolmic** [comment]
Same issue : 

I have multiple consumers, and a producer daemon.

**With php-amqplib 2.6  :** 
If keepalive is true  : 
Consumer exit with "Error reading data. Received 0 instead of expected 7 bytes"
If keepalive is false : 
Consumers work well.

Producer work well in both case

**With amqplib  2.7 :** 
if keepalive is true : 
Consumers work well
Producer fail on second publish() with "Warning: socket_write(): unable to write to socket [104]: Connection reset by peer"
if keepalive is false : 
Consumer exit with "socket_read(): unable to read from socket [104]: Connection reset by peer"
Producer work well

I tried to increase heartbeat/read_write_timeout, but It there is no change.
So I had to rollback to 2.6.3.

**Comment by DemigodCode** [comment]
Exactly the same error "Error sending data. Last SocketError: Connection reset by peer" as @larspohlmann.

I think i have to downgrade to 2.6.x and have to accept the old error "Error reading data. Received 0 instead of expected 7 bytes" ? Or will this be updated?

**Comment by followyounger** [comment]
[2019-06-16 20:28:46] console.ERROR: Error thrown while running command "{command}". Message: "{message}" {"exception":"[object] (PhpAmqpLib\\Exception\\AMQPConnectionClosedException(code: 104): Connection reset by peer at /data/home/www/statistics/src/v20190530185443/vendor/php-amqplib/php-amqplib/PhpAmqpLib/Wire/IO/SocketIO.php:185, ErrorException(code: 0): socket_write(): unable to write to socket [104]: Connection reset by peer at /data/home/www/statistics/src/v20190530185443/vendor/php-amqplib/php-amqplib/PhpAmqpLib/Wire/IO/SocketIO.php:171)","command":"rabbitmq:consumer statistics_device_operation","message":"Connection reset by peer"} []


similar question

**Comment by waxcage** [comment]
Still having the same problem even after years. Is somebody responsible for bug fixing?
