### ISSUE TITLE
RabbitMqBundle Version 2

### ISSUE THREAD

**Issue by skafandri** [php-amqplib/RabbitMqBundle#483]
Looking at pull requests and open issues, reveals that there is a community demand for changes which are not backward compatible, yet very useful. We already have a very valuable [list](https://github.com/php-amqplib/RabbitMqBundle/milestone/1), and probably the [backlog](https://github.com/php-amqplib/RabbitMqBundle/issues) is even larger. 

I suggest to merge bug fixes to [1.x](https://github.com/php-amqplib/RabbitMqBundle/tree/1.x) branch and review existing pull requests and issues for version 2.

I think we can set minimum requirements for the currently supported PHP and Symfony versions. 

Here are some ideas, and let's hear the community voice.
- extensive events, on before_consume, on_ack, on_ack...
- add logs if a logger is available (most probably is)
- allow setup-fabric to create vhosts if the user can
- allow for easier ack/nack (besides returning `true` or `false`) mechanism for better exceptions and edge cases handling.

What do you think people?

**Comment by upyx** [comment]
Hello! I think it is great idea.

Events are very useful to control consuming messages but not only processing ones. Also are useful to control preparing queries and bindings.

Besides I suggest to make it possible to create custom consumer type and add parameter of consumer type into consumer configuration instead configuring hard-coded types of consumers as `multiple_consumers` or `dynamic_consumers`. It will able to do consumers as strategy (pattern) or _more_ dynamic consumers or specific consumer fabric or something else.

What do you mean by easier ack/nack? There are constants of `ConsumerInterface` `MSG_ACK` and `MSG_SINGLE_NACK_REQUEUE`

**Comment by makasim** [comment]
It would be good to migrate to [AMQP Interop](https://github.com/queue-interop/queue-interop#amqp-interop).  This is something I can work on.

**Comment by alcohol** [comment]
> It would be good to migrate to AMQP Interop. This is something I can work on.

Is this still on the backlog?

**Comment by makasim** [comment]
@alcohol FYI https://github.com/php-amqplib/RabbitMqBundle/pull/516 . I've closed it cuz there is no much response on the topic.

**Comment by makasim** [comment]
@alcohol It should take a small effort to run with bunny talking  #516 as a base.

**Comment by ramunasd** [comment]
Version 2 already released.
