### ISSUE TITLE
Deprecated autowiring based on type and class name services

### ISSUE THREAD

**Issue by soullivaneuh** [php-amqplib/RabbitMqBundle#486]
Currently with Symfony 3.4:

```
Autowiring services based on the types they implement is deprecated since Symfony 3.3 and won't be supported in version 4.0. You should rename (or alias) the "old_sound_rabbit_mq.analysis_producer" service to "OldSound\RabbitMqBundle\RabbitMq\ProducerInterface" instead.
```

What should be done:

- Add an alias on the stable version of this bundle and deprecate `old_sound_rabbit_mq.analysis_producer`
- Use directly the `OldSound\RabbitMqBundle\RabbitMq\ProducerInterface` service name.

I got this example but maybe this should be done for other services.

**Comment by nick4fake** [comment]
Just add
````yaml
service_alias:     'OldSound\RabbitMqBundle\RabbitMq\ProducerInterface'
````
