### ISSUE TITLE
Could not run consumer command in Symfony 4.0-BETA4

### ISSUE THREAD

**Issue by infinitely-young** [php-amqplib/RabbitMqBundle#491]
Hi, we have a problem with using of this bundle.
After installing (following this recipe http://flexrecipes.org/recipes/php-amqplib/rabbitmq-bundle), we ran into problem with commands. Their were not added to console environment at all. The same thing works perfect on Symfony 3.2.
We also tried to add consumer command directly to application like this:
```
# file: /bin/console
...
$kernel = new Kernel($env, $debug);
$application = new Application($kernel);
...
// added command
$application->add(new \OldSound\RabbitMqBundle\Command\ConsumerCommand());
...
$application->run($input);
...
```
and execute command
`bin/console rabbitmq:consumer publish_post`
but after that we got exception:
```
The "old_sound_rabbit_mq.publish_post_consumer" service or alias has been removed or inlined when the container was compiled. You should either make it public, or st  
  op using the container directly and use dependency injection instead. 
```
I guess registering of extension that responsible for adding consumer commands is not working properly with Symfony 4

Any idea how to fix it?

**Comment by Vasary** [comment]
+1

**Comment by koktaildotcom** [comment]
In symfony 3.2.x the services are default private within the DI container, making them public prevent the exception: `The "old_sound_rabbit_mq.[....]_consumer" service or alias has been removed or inlined when the container was compiled. You should either make it public, or stop using the container directly and use dependency injection instead.`

See my pull request: https://github.com/php-amqplib/RabbitMqBundle/pull/495

**Comment by asmaHemden** [comment]
have you find a solution for this problem with symfony 4 ?
I have same problem I don't know how to define I use the consumer
