### ISSUE TITLE
What are the reasons behind making BatchConsumer class final?

### ISSUE THREAD

**Issue by FractalizeR** [php-amqplib/RabbitMqBundle#493]
I have a task where I would like to improve behavior of this class (change the way exceptions are handling there). But It's final, whereas Consumer class, that is very similiar to this one is not.

Could we make it open to extension? The whole purpose of providing a parameter like `old_sound_rabbit_mq.batch_consumer.class` looks to me like an extension. `final` directive just makes you copy/paste the class into a new one.

**Comment by amigian74** [comment]
Me too had to copy the whole class, because I wanted to add some additional parameters.

**Comment by ramunasd** [comment]
It's not final anymore.
