### ISSUE TITLE
Is it possible to use AMQPS without a cert with this bundle?

### ISSUE THREAD

**Issue by alexlongshaw** [php-amqplib/RabbitMqBundle#494]
I'm using CloudAMQP hosted RabbitMQ. From their FAQ's, they state the following:

> **Does CloudAMQP support TLS/SSL?**
> We do support TLS (SSL). In most clients is it easy to use TLS, just replace amqp:// with amqps:// in the URL.

I've attempted to do this here but it looks like it's not possible, I just wanted to confirm that's the case.

I've tried setting "amqps" in the url parameter but am getting a malformed url error (which looks to be hardcoded).

_AMQPConnectionFactory_
```
        if ($url === false || !isset($url['scheme']) || $url['scheme'] !== 'amqp') {
            throw new InvalidConfigurationException('Malformed parameter "url".');
        }
```

I'm also having trouble working out where the scheme 'amqp' is coming from in order to adapt it. I assume it must be hardcoded somewhere but I can't seem to find out where.

**Comment by BoShurik** [comment]
@alexlongshaw Hello! How did you solve this issue? Looks like we need to use `PhpAmqpLib\Connection\AMQPSSLConnection`, but bundle does not support this
