### ISSUE TITLE
Input needed: Documentation and Contributing

### ISSUE THREAD

**Issue by alexlongshaw** [php-amqplib/RabbitMqBundle#497]
First of all, thanks for the great work you do in creating/maintaining this repo.

What do people think about adding a contributing information file? Is there a set style guide that any pull requests should be made to etc? I can't really be much help in creating this put maybe some of the contributors could add this?

I've also struggled a bit using the SSL/TLS part of this bundle, I intend on documenting this once I've got it working properly. But on that note, I think that the documentation is a little long for the one file. Perhaps we could split it up or make some parts more concise. I'm happy to work on improving it but it would be good to get a consensus of ideas first? Perhaps a "docs" folder with separate installation.md, getting-started.md files?

Please drop a thumbs up if you think this is a good idea or comment if you have an opinion.

**Comment by alcohol** [comment]
> I've also struggled a bit using the SSL/TLS part of this bundle, I intend on documenting this once I've got it working properly.

Is it just me, or is it simply not possible to actually setup SSL/TLS? Cause I've gone through the configuration setup and the dependency injection parts, but when you all put it together, it seems to me that it is virtually impossible to actually get it to use the SSLConnection class properly.

**Comment by aaronweatherall** [comment]
Any comment on this? I'm struggling to get this to work in November 2019?

**Comment by alexlongshaw** [comment]
@aaronweatherall was quite some time ago now but think I ended up dropping the bundle and using the amqplib package directly.
