### ISSUE TITLE
New tag for symfony 4 fixes

### ISSUE THREAD

**Issue by caciobanu** [php-amqplib/RabbitMqBundle#503]
Hi guys,

I've seen you merged #500. Could you create a new tag ?

Thank you.

**Comment by goetas** [comment]
there is a small bug, see https://github.com/php-amqplib/RabbitMqBundle/pull/507

**Comment by caciobanu** [comment]
Ok. Then after #507 is merged maybe we will get a tag.

**Comment by stloyd** [comment]
Just release `1.14.2` - https://github.com/php-amqplib/RabbitMqBundle/releases/tag/v1.14.2

**Comment by caciobanu** [comment]
Thank you guys!
