### ISSUE TITLE
Link to method name of service on consumer callback

### ISSUE THREAD

**Issue by webdevilopers** [php-amqplib/RabbitMqBundle#514]
Is it possible to link to a method name when configuring the `callback` option on the consumer?

I already have a process manager that I would like to reuse for handling asynch messages.
It would be nice to link to custom method names instead of the `execute` default.

**Comment by webdevilopers** [comment]
Sadly there has been no response for over three years to a rather simple question. I guess the bot will have to close it then.
Most of our projects will be migrated to the Symfony Messenger which supports multiple method calls on event listeners e.g consumers.

**Comment by mihaileu** [comment]
@webdevilopers currently there's no such implementation, but if you really need it, come with a pull request so see how it looks.

**Comment by webdevilopers** [comment]
Thank you for your feedback @mihaileu . As mentioned above we started moving our projects to the Symfony Messenger.
Therefore I'm closing the issue.
