### ISSUE TITLE
Not implementing reset() function in MessageDataCollector is deprecated since Symfony 3.4

### ISSUE THREAD

**Issue by DominikFirla** [php-amqplib/RabbitMqBundle#529]
User Deprecated: Implementing "Symfony\Component\HttpKernel\DataCollector\DataCollectorInterface" without the "reset()" method is deprecated since Symfony 3.4 and will be unsupported in 4.0 for class "OldSound\RabbitMqBundle\DataCollector\MessageDataCollector"

**Comment by ramunasd** [comment]
Already fixed.
