### ISSUE TITLE
best practice for listening rabit server and run / manage php workers  

### ISSUE THREAD

**Issue by grekpg** [php-amqplib/RabbitMqBundle#532]
like in title - best practice for listening rabit server and run / manage php workers  , there is some application witch keep alive listen rabitmq new messages and run php - one or many consumers ? i think cron is not best concept 

i found - https://github.com/ricbra/rabbitmq-cli-consumer 

but this overwrite RabbitMqBundle consumer managing.

**Comment by lushc** [comment]
It's not mentioned in the README, but when it comes to management of consumer processes I don't think anything can beat the [RabbitMQ supervisor bundle](https://github.com/Phobetor/rabbitmq-supervisor-bundle).
