### ISSUE TITLE
Release the fix for #520

### ISSUE THREAD

**Issue by nicwortel** [php-amqplib/RabbitMqBundle#537]
Issue #520 has been fixed by PR #509, but no new version has been tagged ever since. Could you release a new version containing this fix?

Thanks very much in advance!

**Comment by frankdejonge** [comment]
For everybody waiting on this, I've worked around this using:

```php
<?php

namespace App\DependencyInjection;

use Symfony\Component\DependencyInjection\Compiler\CompilerPassInterface;
use Symfony\Component\DependencyInjection\ContainerBuilder;

class MakeOldsoundServicePublicPass implements CompilerPassInterface
{
    /**
     * You can modify the container here before it is dumped to PHP code.
     */
    public function process(ContainerBuilder $container)
    {
        $container->getDefinition('old_sound_rabbit_mq.parts_holder')->setPublic(true);
    }
}
```

**Comment by nicwortel** [comment]
Update for everyone watching this: [v1.14.3](https://github.com/php-amqplib/RabbitMqBundle/releases/tag/v1.14.3) has been released, [containing the fix](https://github.com/php-amqplib/RabbitMqBundle/pull/509/commits/e5d253f18a53f65725095d83a75bff99a4ff2090), so I'm closing this issue :+1:

**Comment by frankdejonge** [comment]
@nicwortel thank you! 👍
