### ISSUE TITLE
Symfony 3.4+ batch consumers

### ISSUE THREAD

**Issue by Hast** [php-amqplib/RabbitMqBundle#541]
Batch consumers are generated as private service which is depricated since symfony 3.4:

`Checking for the initialization of the "old_sound_rabbit_mq.batch_consumer" private service is deprecated since Symfony 3.4 and won't be supported anymore in Symfony 4.0.`

**Comment by fidraj** [comment]
I have the same problem and I haven't been able to find a solution for it. Apparently this notice pops-up in tests when tearDown of all bundles is called. Same for RPC servers. https://github.com/php-amqplib/RabbitMqBundle/blob/df086947be62278bb3d42ee22cdd791cc908a839/OldSoundRabbitMqBundle.php#L23-L35

**Comment by Siembrink** [comment]
At the moment there is no way to use batch consumer in Symfony 4. The PR will fix this.
