### ISSUE TITLE
Symfony 4 support

### ISSUE THREAD

**Issue by jamalo** [php-amqplib/RabbitMqBundle#543]

**Comment by kejwmen** [comment]
Could you explain what exactly does not work?
Support is here for some time https://github.com/php-amqplib/RabbitMqBundle/releases

**Comment by simivar** [comment]
@kejwmen description of package is misleading. It states that this package is only for Symfony **2** appliactions when in reality it works with Symfony 3 and 4 too.

**Comment by kejwmen** [comment]
you're right, thanks you found some time to prepare a PR!

**Comment by tezrik** [comment]
` INFO      [php] User Deprecated: The "OldSound\RabbitMqBundle\Event\AMQPEvent" class extends "Symfony\Component\EventDispatcher\Event" that is deprecated since Symfony 4.3, use "Symfony\Contracts\EventDispatcher\Event" instead.
[
  "exception" => ErrorException {
    #message: "User Deprecated: The "OldSound\RabbitMqBundle\Event\AMQPEvent" class extends "Symfony\Component\EventDispatcher\Event" that is deprecated since Symfony 4.3, use "Symfony\Contracts\EventDispatcher\Event" instead."
`

**Comment by jaztec** [comment]
Also relevant at: https://github.com/php-amqplib/RabbitMqBundle/blob/master/RabbitMq/BaseAmqp.php#L271

```
User Deprecated: Calling the "Symfony\Component\EventDispatcher\EventDispatcherInterface::dispatch()" method with the event name as first argument is deprecated since Symfony 4.3, pass it second and provide the event object first instead. {"exception":"[object] (ErrorException(code: 0): User Deprecated: Calling the \"Symfony\\Component\\EventDispatcher\\EventDispatcherInterface::dispatch()\" method with the event name as first argument is deprecated since Symfony 4.3, pass it second and provide the event object first instead. at /path/to/project/vendor/symfony/event-dispatcher/Debug/TraceableEventDispatcher.php:148)"}
```

**Comment by roslov** [comment]
Any estimations when it goes to a release?

**Comment by thomaspicquet** [comment]
Would be nice to get an update but it doesn't look like this bundle is maintained anymore, no new version since may 2018? :(

**Comment by simivar** [comment]
@roslov @thomaspicquet from what I gathered last year the bundle worked fine. Right now you have official [symfony/messenger](https://github.com/symfony/messenger) component and I would recommend that you use it if you can. [Here are the docs](https://symfony.com/doc/4.1/messenger.html#transports).

**Comment by roslov** [comment]
@simivar, for some reason we cannot upgrade one of our services from Symfony 3.4 to Symfony 4.x. The messenger was introduced in 4.1; so we cannot use it.

**Comment by simivar** [comment]
@roslov If I can ask one question then so I can understand fully. If you are using Symfony 3.4 why are you posting in issue regarding Symfony 4 support? What's your issue?

**Comment by roslov** [comment]
@simivar, it's about a deprecation note which is shown on 3.4.

**Comment by kejwmen** [comment]
@roslov why you can't? Bundle is compatible for some time.

**Comment by roslov** [comment]
@kejwmen, I cannot upgrade not because of this bundle but because of other dependencies and some legacy parts of code.

**Comment by kejwmen** [comment]
@roslov could you post more details or link them here? Sorry, I didn't follow.

**Comment by jaztec** [comment]
[Thanks](https://github.com/php-amqplib/RabbitMqBundle/issues/543#issuecomment-524018601) for this update @simivar, I somehow missed the usages of that bundle.

@roslov If the `finger_crossed` monolog handler is biting you (as it was for me since it kept all deprecation messages in memory and ran out of process memory on big jobs because of it), it is kind of a dirty fix but it works; you can alter the framework settings on that environment/job:
```
framework:
    php_errors:
        log: false
```

**Comment by simivar** [comment]
@roslov but from what I see this deprecation message was [added in Symfony 4.3](https://github.com/symfony/event-dispatcher/blob/4.3/EventDispatcher.php#L58). You can see that [it wasn't there in 4.2](https://github.com/symfony/event-dispatcher/blob/4.2/EventDispatcher.php#L37) or lower. That means that you are using Symfony 3.4 with event dispatcher from 4.3?

@nubeiro is there anyone who can take care of this bundle? Maybe you are looking for some help?

@lukebakken @ramunasd I see that you are taking care of [php-amqplib/php-amqplib](https://github.com/php-amqplib/php-amqplib). Do you maybe have `Collaborator` rank in here?

**Comment by mihaileu** [comment]
use the latest tag for sy4.3/5 compatibility
