### ISSUE TITLE
Memory leak or something else ?

### ISSUE THREAD

**Issue by benjaminb-** [php-amqplib/RabbitMqBundle#545]
I have some workers running with RabbitMqBundle and managed by Supervisor in my Docker stack.

The Supervisor container (which is running the workers) have a big memory leak. (green line).

This is my supervisor configuration for the worker

```
[program:aps_get_distant_image]
command=php /var/www/bin/console rabbitmq:consumer -m 50 aps_get_distant_image --env=prod --no-debug
process_name = aps_get_distant_image_%(process_num)s
numprocs = 3
autostart=true
autorestart=true
startretries=10
stderr_logfile=/var/log/worker_aps_get_distant_image.err.log
stdout_logfile=/var/log/worker_aps_get_distant_image.out.log
priority=2
```

The red line is the php process.

<img width="893" alt="qhv0e" src="https://user-images.githubusercontent.com/2737761/38738596-d4f28764-3f32-11e8-9dda-bc2b12955fa1.png">

The purpose of the worker is :

* Make a small query to get some informations in the gallery mysql table
* Check if a file exists in the DB (with the filename)
* If not : Open an FTP connection (with Flysystem) to download the file and persist a row

I made a lot of optimisations on the workers

* open and close the Doctrine entity manager at each execution
* disable Monolog fingers_crossed
* unset() doctrine objects and all variables used
* clear entity manager
* close ftp connections

I suppose this kind of process can consume a lot of memory ? Because of the FTP connexion maybe ?

The memory keeps growing, i have a cron which restart the supervisor container to free the memory each 6 hours, but i'm afraid. If i add more galleries, it will be more files download, FTP connections, etc. 

Does anyone have any tips or had a similar problem ? Or any optimisations tips ?

I can provide more informations if needed.

Thanks :)

**Comment by sane4ek-2** [comment]
Hi @benjaminb- . Are you confident the problem is in this bundle? Did you check other parts of your consumer. Try to remove the body of your consumer and measure memory consumption with option `--env=prod`. I think the problem will be off. After that add lines of the body iteratively and do measurement of memory consumption.

I had the same problem. I found out that bulk piece of the problem was in DoctrineORM and some in my code.

**Comment by roslov** [comment]
> use `--memory-limit` option when start a consumer. It resolves the problem o memory leaking of PHP.

Is there any memory limit option for `rabbitmq:rpc-server`? Not only for `rabbitmq:multiple-consumer` / `rabbitmq:consumer`.
