### ISSUE TITLE
New release?

### ISSUE THREAD

**Issue by roelmonnens** [php-amqplib/RabbitMqBundle#547]
Is it possible to create a new minor release?
There are 8 PRs merged to master that improve this library greatly.

Thnx

**Comment by lushc** [comment]
Just ran into an issue because #468 hasn't been released yet, so a new release would be very welcome 👍

**Comment by notrix** [comment]
👍

**Comment by Siembrink** [comment]
Just found out that there is a new release!

**Comment by skafandri** [comment]
https://github.com/php-amqplib/RabbitMqBundle/releases/tag/v1.14.4
