### ISSUE TITLE
There are no commands defined in the "rabbitmq-supervisor" namespace 

### ISSUE THREAD

**Issue by jvkiran** [php-amqplib/RabbitMqBundle#549]
I'm new to symfony

I'm using Symfony 3.4.9 (kernel: app, env: prod, debug: false).

I simply ran below commands:
 "sudo apt install -y rabbitmq-server" & sudo apt-get install -y supervisor and then composer install

i'm using this repo [superdesk](https://github.com/superdesk/web-publisher)

command: sudo -u www-data SYMFONY_ENV=prod php app/console rabbitmq-supervisor:build --env=prod

error: There are no commands defined in the "rabbitmq-supervisor" namespace

Also rabbitmq-server and supervisor both services are running in production server.

**Comment by thehatami** [comment]
same issue

**Comment by ramunasd** [comment]
AFAIK we never had such command.
