### ISSUE TITLE
What does heartbeat: 0 mean?

### ISSUE THREAD

**Issue by echonox** [php-amqplib/RabbitMqBundle#552]
Does it mean heartbeat is not used, or does it mean default timeout is 60s (as rabbitmq docs say)

**Comment by garjitzky-movidius** [comment]
From my understanding, if you set heartbeat to 0 on your Consumers then they will apply the RabbitMQ Server's heartbeat value(which by default is 60 or can be set inside the /etc/rabbitmq/rabbitmq.config file)

**Comment by ramunasd** [comment]
0 means that You are accepting heartbeat value from peer. Both peers must suggest 0 in order to disable heartbeats completely.

https://www.rabbitmq.com/heartbeats.html
