### ISSUE TITLE
Monitoring

### ISSUE THREAD

**Issue by helmut-hoffer-von-ankershoffen** [php-amqplib/RabbitMqBundle#561]
Hi,

what is the recommended way to monitor if a consumer is running and ready to consume messages?

We are running a Docker Swarm with Sf4 based nodes spawning consumer processes.

Best

**Comment by oleg-andreyev** [comment]
The best way to monitor consumers and Rabbit MQ itself is to use Management plugin https://www.rabbitmq.com/management.html

**Comment by estahn** [comment]
@helmuthva Wouldn't you rather monitor the queue instead of the consumer? As long as the messages are consumed within defined SLO/SLIs then everything should be fine.

**Comment by makasim** [comment]
`enqueue\monitoring` could be integrated into the bundle so you can get stats in real time or any other analytics platform (such as grafana). 

https://github.com/php-enqueue/monitoring
