### ISSUE TITLE
While a consumer is running the data fetched from doctrine is the same even when it changes

### ISSUE THREAD

**Issue by sinner** [php-amqplib/RabbitMqBundle#564]
I'm running a consumer as:

```sh
bin/console rabbitmq:consumer send_email_messages
```
I'm fetching the email data of who must receive the email from our transactional database using doctrine. If I send an email message the first time it's sending the message correctly but while I'm still running the consumer if I change the email of the same user and send another email (adding another element to the queue) to this user but with a different email, the consumer sends the email to the previous email and this change is not applied until after stopping the consumer and running it again.

So while a consumer is running the data fetch from doctrine is the same even when it changes.

Note: I'm clearing the entity and I'm applying an unset on the variables even but it's not working.

```php
$messageTargets = $em->getRepository(MessageTarget::class)->findBy(['message' => $message]);

# ... Loop for sending email messages...

$em->clear($messageTargets);
unset($messageTargets)
```

**Comment by sinner** [comment]
Note: I'm clearing the entity and I'm applying an unset on the variables even.

```php
$messageTargets = $em->getRepository(MessageTarget::class)->findBy(['message' => $message]);

# ... Loop for sending email messages...

$em->clear($messageTargets);
unset($messageTargets)
```

**Comment by paullla** [comment]
Hi @sinner, did you manage to find the solution?

**Comment by Russellmd** [comment]
The same issue with Symfony4 + Enqueue + rabbitmq. Only 
`$em->refresh($object);`
helps me, but I don't like to use one more request only for this...
