### ISSUE TITLE
Could it be this library compatible with Amazon MQ?

### ISSUE THREAD

**Issue by sinner** [php-amqplib/RabbitMqBundle#565]
Could it be this library compatible with Amazon MQ? Because I've tried to use it with this service provided by Amazon MQ and it wasn't successful.

**Comment by makasim** [comment]
Unfortunately not cuz Amazon MQ uses AMQP 1.0 and this bundle uses 0.9.1. It is two completely different protocols.

**Comment by dixromos98** [comment]
any changes on this?

**Comment by linuxtm** [comment]
It would be really useful to support AMQP 1.0 so we can use AmazonMQ with Magento2 instead of having to provision our own Rabbit server and then deal with monitoring, autoscaling, etc.

**Comment by ramunasd** [comment]
Already answered in https://github.com/php-amqplib/php-amqplib/issues/757
