### ISSUE TITLE
Sending SIGTERM causes exception

### ISSUE THREAD

**Issue by alterphp** [php-amqplib/RabbitMqBundle#567]
Hello,

I'm using php consumers with php-amqplib/RabbitMqBundle. Since php-amqplib/php-amqplib is upgraded to 2.8.0, I encounter an error when sending a SIGTERM signal to the consumer process (see https://github.com/php-amqplib/php-amqplib/issues/611).

I expect that SIGTERM is the good signal to make onprocess messages being properly terminated. But the exception makes the process to hardly fail...

Running the consumer with option `without-signal` prevent from SIGTERM to throw exception but I lose the proper termination of onprocess messages...

Is that a bug or a bad use of consumers ?

**Comment by alterphp** [comment]
Here is the stacktrace

```

**Comment by spectrox** [comment]
I am having same issue on 2.8.1 (migrated a few weeks ago from 2.7.2).

Take a look here:
https://github.com/php-amqplib/php-amqplib/commit/ef318f10927f5b5c1530ada9018a714571014352#diff-593ddf6cbc93f7e4518ba0d20c13a8d7R333

The message @alterphp mentions ("Interrupted system call") were skipped in the past as a normal behavior. And there was even a comment for that:
> stream_select warning that it has been interrupted by a signal

And as you can see the message shown by @alterphp doesn't have `errno=`.

My error message doesn't have `errno` mentions too:
```
/vendor/php-amqplib/php-amqplib/PhpAmqpLib/Wire/IO/StreamIO.php:473: stream_select(): unable to select [4]: Interrupted system call (max_fd=7)
```

**Comment by alterphp** [comment]
Thanks @spectrox for your feedback ! I close issue here.
