### ISSUE TITLE
BatchConsumer have strange timeout_wait behavior

### ISSUE THREAD

**Issue by Mogidin** [php-amqplib/RabbitMqBundle#577]
Expected behavior - after the first message is received, process all batched messages after **timeout_wait** sec maximum.
Example: prefetch = 10, timeout_wait = 5 sec
00:00:20 - message 1
00:00:22 - message 2
00:00:24 - message 3
batchConsume

Current behavior:
prefetch = 10, timeout_wait = 5 sec
00:00:20 - message 1
00:00:22 - message 2
00:00:24 - message 3
...
00:00:38 - message 10
batchConsume
it's very long waiting, especially with large prefetch_count and temporary message rate reduction

Or need new parameter

**Comment by ramunasd** [comment]
I guess You didn't understand what exactly those parameters means :)
prefetch - it's how much messages consumer should take and hold in memory buffer, those messages are reserved for current consumer and won't be dispatched to other consumer.
timeout_wait - this not maximum consume time, from README _The `timeout_wait` specifies how long the consumer will wait without receiving a new message before ensuring the current connection is still valid._
