### ISSUE TITLE
Producer service not found in symfony 4

### ISSUE THREAD

**Issue by zim32** [php-amqplib/RabbitMqBundle#579]
Hi I just setup basic example in symfony 4.2.3

**config/packages/old_sound_rabbit_mq.yaml:**
```
old_sound_rabbit_mq:
    connections:
        default:
            url: '%env(RABBITMQ_URL)%'
    producers:
        # use 'old_sound_rabbit_mq.task_producer' service to send data.
        task:
            connection:       default
            exchange_options: { name: 'task', type: direct }
            service_alias: task_producer
    consumers:
        task:
            connection:       default
            exchange_options: { name: 'task', type: direct }
            queue_options:    { name: 'task'}
            callback:         App\Component\RabbitMQ\Consumer\TaskConsumer
```

**In controller:**
$this->get('old_sound_rabbit_mq.task_producer')->publish(json_encode($msg));

**Got error:**
Service "old_sound_rabbit_mq.task_producer" not found: even though it exists in the app's container, the container inside "App\Controller\DomainsController" is a smaller service locator that only knows about the "doctrine", "form.factory", "http_kernel", "parameter_bag", "request_stack", "router", "security.authorization_checker", "security.csrf.token_manager", "security.token_storage", "serializer", "session" and "twig" services. Try using dependency injection instead.

Using service alias cause the same error.

Any suggestions? Thanks.

**Comment by amigian74** [comment]
I've a similiar issue getting the producer service with Symfony 4.2

The "...." service or alias has been removed or inlined when the container was compiled. You should either make it public, or stop using the container directly and use dependency injection instead.

**Comment by zim32** [comment]
This issue relates to new thing in symfony called service locators. But i can not figure out how to make it to work with this bundle

**Comment by zim32** [comment]
Your case is different. For private services (i think this is default) it means you can not get service directly from container->get method and must inject dependency in constructor or action method as argument. Symfony track this dependencies and remove unused services from final compiled container.

**Comment by amigian74** [comment]
That's true. But this makes things much more complicated. It would be nice (and in my opinion with Symfony 4 support) it should be possible, to mark producer services as public.

**Comment by zim32** [comment]
Yeah I think it should be fixed in this bundle to make it possible to get service from container and to prevent it from being inlined

**Comment by kubec** [comment]
Working solution: https://stackoverflow.com/a/49858447

**Comment by shadz3rg** [comment]
You always can bind producer service as common argument in service.yml
```
services:  
    _defaults:  
        bind:  
            $pingProducer: '@old_sound_rabbit_mq.ping_producer'  
```

**Comment by zim32** [comment]
This is solution

**Comment by reneszabo** [comment]
> You always can bind producer service as common argument in service.yml
> 
> ```
> services:  
>     _defaults:  
>         bind:  
>             $pingProducer: '@old_sound_rabbit_mq.ping_producer'  
> ```

What do you mean by this ?
