### ISSUE TITLE
stream_select(): unable to select

### ISSUE THREAD

**Issue by coderaf** [php-amqplib/RabbitMqBundle#580]
Hey, im on version "v1.14.4" . 
PHP 7.2. 
symfony/symfony:3.4 . 
  
 still got

>  ErrorException: stream_select(): unable to select [4]: Interrupted system call (max_fd=8)
in /php-amqplib/php-amqplib/PhpAmqpLib/Wire/IO/StreamIO.php line 461. 

It happens every deploy, when consumers are set.

**Comment by rahulsharma20** [comment]
I am getting the same exception.
php-amqplib/RabbitMqBundle version "v1.14.4"
PHP 5.6
Symfony 2.8

Doesn't happen on every time but yeah once in a while.

> [ErrorException]                                                           
  stream_select(): unable to select [4]: Interrupted system call (max_fd=5)  
                                                                            rabbitmq:consumer [-m|--messages [MESSAGES]] [-r|--route [ROUTE]] [-l|--memory-limit [MEMORY-LIMIT]] [-d|--debug] [-w|--without-signals] [-h|--help] [-q|--quiet] [-v|vv|vvv|--verbose] [-V|--version] [--ansi] [--no-ansi] [-n|--no-interaction] [-s|--shell] [--process-isolation] [-e|--env ENV] [--no-debug] [--] <command> <name>

**Comment by ramunasd** [comment]
This looks like library issue, not the bundle actual. Please report for php-amqplib/php-amqplib if You still experience that.
Also, do not forget to update to latest version.
