### ISSUE TITLE
Add possibility to manually kill the consumer

### ISSUE THREAD

**Issue by henri9813** [php-amqplib/RabbitMqBundle#583]
Hello,

When i use CTRL+C to kill the consumer, nothing happen and i have to close my terminal which is pretty annoying, 
```
$ php bin/console rabbitmq:batch:consumer my_consumer
^C^C

```

How can i kill a batch consumer ? 

Best regards

**Comment by Kolbasyatin** [comment]
If You want to kill batch consumer manually, use -w flag.
`$ php bin/console rabbitmq:batch:consumer my_consumer -w`

**Comment by henri9813** [comment]
Hello,

Thanks for your answer, is it possible to add it by default ? 

Regards

**Comment by Kolbasyatin** [comment]
I'm not sure... Maybe in config of bundle? But there is no problem add -w in console command, isn't it ? Or You can start consumer by Seprvisor. Describe your command in appropriate config file.

**Comment by henri9813** [comment]
Hello @Kolbasyatin,

Not especially except is not explained in the documentation, so...

But it should be a default parameter in my opignion, if think they is no interest to add a parameter to get the possibility to kill a consumer like i would kill another process :/ 

Thanks for your answer! :-) 

Regards,
Henri Devigne

**Comment by ramunasd** [comment]
This option is misleading.
When enabled `--without-signals` You will halt process immediatelly, in the middle of processing current message.
Without this option the process will stop right after current message and exits gracefully. If it's not - then please submit another related issue.
