### ISSUE TITLE
Can't produce messages without defining a consumer

### ISSUE THREAD

**Issue by moofik** [php-amqplib/RabbitMqBundle#586]
In my app I need to produce messages for queue and consumer for this queue is node.js application, so I don't need PHP consumer. But I can't define producer but not to define consumer because Symfony container states an error: << You have requested a non-existent service "old_sound_rabbit_mq.websocket_notifications_consumer" >>
Is there any way to do this with RabbitMqBundle (create and use producer without consumer)? Any suggestions?

**Comment by kgrosvenor** [comment]
I need to know how to do this too!

**Comment by ramunasd** [comment]
You can. Just use correct exchange/queue name and message format.
