### ISSUE TITLE
Delete Command is not working

### ISSUE THREAD

**Issue by llegaz** [php-amqplib/RabbitMqBundle#593]
**$ ps aux | grep consum**
13185  0.0  0.2 337764 48248 pts/2    S    18:04   0:00 php bin/console rabbitmq:consumer elastic_doctrine_duplicate -vvv --env=dev

**$ bin/console rabbitmq:delete --no-confirmation elastic_doctrine_duplicate**

In AMQPChannel.php line 188:
                                                                                
  PRECONDITION_FAILED - queue 'elastic_doctrine_duplicate' in vhost '/' in use  
                                                                                

rabbitmq:delete [--no-confirmation] [-h|--help] [-q|--quiet] [-v|vv|vvv|--verbose] [-V|--version] [--ansi] [--no-ansi] [-n|--no-interaction] [-e|--env ENV] [--no-debug] [--] <command> <name>

**$ ps aux | grep consum**
13185  0.0  0.2 337764 48248 pts/2    S    18:04   0:00 php bin/console rabbitmq:consumer elastic_doctrine_duplicate -vvv --env=dev

**Comment by ramunasd** [comment]
So it's not a bundle issue. You really cannot delete a queue while consumers are connected to it.
