### ISSUE TITLE
Swiftmailer doesn't work with the consumers

### ISSUE THREAD

**Issue by saleh199** [php-amqplib/RabbitMqBundle#597]
Hello,

Sending emails in Symfony by using Swiftmailer and the spool type as `memory` from a consumer, needs one of these events `KernelEvents::TERMINATE` or `ConsoleEvents::TERMINATE` so it became an issue in this case while there are no events fired for that.

**Comment by saleh199** [comment]
https://github.com/symfony/swiftmailer-bundle/blob/master/EventListener/EmailSenderListener.php

**Comment by Gingonic** [comment]
I had success with following this: https://symfony.com/doc/2.0/cookbook/console/sending_emails.html
In a nutshell deactivate spooling.
This is not an issue with the RabbitMqBundle itself.
