### ISSUE TITLE
is this project maintained anymore? 

### ISSUE THREAD

**Issue by johnsnowderomania** [php-amqplib/RabbitMqBundle#600]
Hello, 

I see that the last update is 7 months ago and there are 139 issues and 43 PR open. Is this project maintained anymore?

**Comment by dvdknaap** [comment]
I think this project is dead, is there someone that knows a similar bundle ?

**Comment by mythxxx** [comment]
> I think this project is dead, is there someone that knows a similar bundle ?

For Symfony > 4.1 you can use Symfony Messenger, but for earlier versions... not much luck.

**Comment by Snake-Tn** [comment]
@johnsnowderomania this is not maintained any more, contributors with write access have either passed away or not available any more to do PR merging and so.

**Comment by dixromos98** [comment]
@dvdknaap i know it's late but https://github.com/swarrot/SwarrotBundle maybe what you need

**Comment by mihaileu** [comment]
We receive access to this repo and now it has mantainers.
