### ISSUE TITLE
Phpunit error, sandbox doesn`t help

### ISSUE THREAD

**Issue by e1sep0** [php-amqplib/RabbitMqBundle#603]
Hello. I want to disable rabbit errors while Phpuinit testing, but in always try to connect to rabbit. How can i pass tests without rabbit? Thank you

**Comment by e1sep0** [comment]
in config_test.yml
`old_sound_rabbit_mq:
    sandbox: true`
I get error, when `$this->getContainer()` is called.

**Comment by Eloar** [comment]
could you provide your phpunit output? Are u using phpunit from vendor or other instance?

**Comment by ramunasd** [comment]
No answer since 2019.
