### ISSUE TITLE
batch:consume does not emit any event after cycle

### ISSUE THREAD

**Issue by sakalys** [php-amqplib/RabbitMqBundle#604]
`\OldSound\RabbitMqBundle\RabbitMq\BatchConsumer::batchConsume` does not emit any event after a consume. Compared to `\OldSound\RabbitMqBundle\RabbitMq\Consumer::processMessageQueueCallback` which emits a `\OldSound\RabbitMqBundle\Event\AfterProcessingMessageEvent`.

Id say this is inconsistent...

**Comment by mp3000mp** [comment]
Hi, are you open for a PR on this topic ?

**Comment by speech77** [comment]
hi, any news on this topic? `BatchConsumer` does not fire any `AMQPEvent` at all!!

**Comment by speech77** [comment]
This issue is closed, I opened a new issue https://github.com/php-amqplib/RabbitMqBundle/issues/730

**Comment by speech77** [comment]
I hope I didn't make a mistake :)
