### ISSUE TITLE
compatibility with sf5

### ISSUE THREAD

**Issue by d-r-e-w** [php-amqplib/RabbitMqBundle#613]
Is it in this project's plans?

**Comment by mihaileu** [comment]
check this comment: 
https://github.com/php-amqplib/RabbitMqBundle/pull/605#issuecomment-583001238

**Comment by mihaileu** [comment]
We added the changes from emag repo here, now you have the compatibility with sy5.
The repository from emag namespace will be marked as abandoned in order to keep only one repo up.
