### ISSUE TITLE
Reconnect consumer

### ISSUE THREAD

**Issue by alejandrojsn** [php-amqplib/RabbitMqBundle#618]
I need to reconnect a consumer when AMQPConnectionClosedException is thrown.

I tried to wrap the execute method of the consumer command on a try catch, and in the catch I use the reconnect() method of the consumer instance, an then consume() again.
However, when consume() is run again, the same error is thrown...

**Comment by ramunasd** [comment]
Wouldn't it be easier just increase timeouts, enable heartbeats and keepalive? Lastly, if connection was closed by peer, then it's a good opportunity to restart whole process and refresh memory usage.
