### ISSUE TITLE
when will there be support symfony 5?

### ISSUE THREAD

**Issue by StasToken** [php-amqplib/RabbitMqBundle#619]
Symfony 5.1.3
composer require php-amqplib/rabbitmq-bundle
Using version ^1.14 for php-amqplib/rabbitmq-bundle
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Restricting packages listed in "symfony/symfony" to "5.1.*"
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - php-amqplib/rabbitmq-bundle v1.14.4 requires symfony/dependency-injection ^2.7|^3.0|^4.0 -> no matching package found.
    - php-amqplib/rabbitmq-bundle v1.14.3 requires symfony/dependency-injection ^2.7|^3.0|^4.0 -> no matching package found.
    - php-amqplib/rabbitmq-bundle v1.14.2 requires symfony/dependency-injection ^2.7|^3.0|^4.0 -> no matching package found.
    - php-amqplib/rabbitmq-bundle v1.14.1 requires symfony/dependency-injection ^2.7|^3.0|^4.0 -> no matching package found.
    - php-amqplib/rabbitmq-bundle v1.14.0 requires symfony/dependency-injection ^2.7|^3.0|^4.0 -> no matching package found.
    - Installation request for php-amqplib/rabbitmq-bundle ^1.14 -> satisfiable by php-amqplib/rabbitmq-bundle[v1.14.0, v1.14.1, v1.14.2, v1.14.3, v1.14.4].

Potential causes:
 - A typo in the package name
 - The package is not available in a stable-enough version according to your minimum-stability setting
   see <https://getcomposer.org/doc/04-schema.md#minimum-stability> for more details.
 - It's a private package and you forgot to add a custom repository to find it

Read <https://getcomposer.org/doc/articles/troubleshooting.md> for further common problems.

Installation failed, reverting ./composer.json to its original content.

**Comment by god1dog** [comment]
The update is being discussed here https://github.com/php-amqplib/RabbitMqBundle/pull/605

**Comment by kirya-dev** [comment]
Migration process is too slowly..
Just use https://github.com/php-amqplib/php-amqplib

**Comment by mihaileu** [comment]
https://github.com/php-amqplib/RabbitMqBundle/pull/605#issuecomment-583001238
there's another fork that is maintained and it offer support for sy5: https://packagist.org/packages/emag-tech-labs/rabbitmq-bundle

**Comment by mihaileu** [comment]
We managed  to receive access to this repo and we will migrate back here from emag-tech-labs namespace because we believe that this is the best option for now, in order to not keep two repos with split community. We will close old issues and PRs because most probably there are not relevant now.

For using the latest version, which have sy5 compatibility, please switch your the major tag ^2.5.1.

**Comment by kirya-dev** [comment]
Thks. already used
