### ISSUE TITLE
Consumer throws: "Missed server heartbeat"

### ISSUE THREAD

**Issue by amanangira** [php-amqplib/RabbitMqBundle#636]
Hi, my application has numerous consumers running over years now. These are containerized and deployed on Kubernetes where each consumer has a dedicated pod for itself. 

Recently I started facing numerous `fwrite() Connection was reset by beer` exceptions and to handle that I created a new connection as the following and used it in my consumer.

Connection 
```
default_with_updated_timeout:
            host:     '%rabbit.host%'
            port:     '%rabbit.port%'
            user:     '%rabbit.user%'
            password: '%rabbit.password%'
            vhost:    '%rabbit.vhost%'
            lazy:     true
            connection_timeout: 300
            read_write_timeout: 900

            # requires php-amqplib v2.4.1+ and PHP5.4+
            keepalive: false

            # requires php-amqplib v2.4.1+
            heartbeat: 450

```

Consumer
```
x_y_event:
            connection:       default_with_updated_timeout
            exchange_options: {name: 'x-y-event', type: topic}
            queue_options:
                name:         'x-y-event'
                arguments:
                    x-message-ttl: ['I', 14400000] # 4 hours
                    x-dead-letter-exchange: ['S', 'x-y-event']
                    x-dead-letter-routing-key: ['S', 'dead.x-y-event']
                routing_keys:
                      - 'x-y-event'
            callback:         service.alias
            qos_options:
                prefetch_count: 1
```
The thought behind was that the consumer might have been taking longer to process and acknowledge therefore the server was receiving no acknowledgments for heartbeats. And hence the heartbeat timeout was increased and so was read_write_timeout.

Now although the `fwrite() Connection was reset by beer` is gone and seems to be fixed I have started seeing "Missed server heartbeat". Just to be clear "Missed server heartbeat" was present before creating and using the above new connection as well. 

Now because of this, my pod has witnessed numerous restarts. Although currently it doesn't seem we have lost any messages but in my understanding, this scenario should be already handled by `StreamIO::reconnect()`

Symfony version - 3.4
RabbitMQBundle version - v1.14.4
<img width="1125" alt="Screenshot 2021-05-13 at 1 49 32 PM" src="https://user-images.githubusercontent.com/19432766/118099049-57b6fe00-b3f2-11eb-9f84-d030816d8c8b.png">

**Comment by hugosoltys-dkt** [comment]
Any updates on this ? We have the same problem here.

**Comment by itinance** [comment]
What is the better approach to deal with long-running consumer tasks? split them into smaller chunks? or reject messages with `requeue=true` ?

**Comment by itinance** [comment]
I found a way how to deal with long-running tasks to avoid this exception:

In the consumer we need to call a `wait`-function on the RabbitMQ connection from time to time. I do this in a loop with some modulo-approach for executing this wait-function on every 5th  loop and this way I have never seen this exception any more. It is like "doEvents" in VB-programs 1989 :) or `application.processMessages` in Delphi 1996.

```
                $funcWait = function() use ($msg) {
                    $msg->getChannel()->getConnection()->wait(null, true);
                };

                $this->produceEditionForProduct($data['productId'], $funcWait);
```

**Comment by mtreuberg** [comment]
Here's another approach: https://blog.mollie.com/keeping-rabbitmq-connections-alive-in-php-b11cb657d5fb
