### ISSUE TITLE
configuration for rabbitmq tls / amqps 

### ISSUE THREAD

**Issue by yandok** [php-amqplib/RabbitMqBundle#641]
Hi!

I have a rabbitmq server exposing tls port at 5671. 

When configuring the old_sound_rabbit_mq (2.7.0, 2.6.3) with

```
url: 'amqps://%env(RABBITMQ_USER)%:%env(RABBITMQ_PASSWORD)%@%env(RABBITMQ_HOST)%:%env(RABBITMQ_PORT)%'
vhost: '%env(RABBITMQ_VHOST)%'
lazy: true
connection_timeout: 30
read_write_timeout: 30
ssl_context:
  verify_peer: false
keepalive: true
heartbeat: 10
use_socket: false # default false
```

I'm getting "`Broken pipe or closed connection`". When setting `use_socket: true`  the return message is: "`Warning: socket_recv(): unable to read from socket [104]: Connection reset by peer`". Is it possible to use the bundle with rabbit mq tls port and how do I configure it correctly?

Everythink works fine with non-tls port 5762 but we are forced to use TLS.

Thanks in advance

**Comment by unki** [comment]
could it be, that the bundle passes the option `ssl_context` to PhpAmqpLib\Connection\AMQPStreamConnection, but the later is actually looking for just `context` (here in [L92](https://github.com/php-amqplib/php-amqplib/blob/master/PhpAmqpLib/Connection/AMQPStreamConnection.php#L92)). When I change these two lines to use `ssl_context`

```php
        $context = isset($options['ssl_context']) ?
                         $options['ssl_context'] : null;
```

SSL/TLS support starts working again. Without that, phpAmqpLib actually attempts to connect plaintext on the SSL/TLS RabbitMQ-port

**Comment by winus** [comment]
I have created pr https://github.com/php-amqplib/RabbitMqBundle/pull/648 , think this is related.

**Comment by mihaileu** [comment]
@yandok we merged the previous PR, could you please check if you still have this issue?
