### ISSUE TITLE
how create exchange, and queue.

### ISSUE THREAD

**Issue by xorgxx** [php-amqplib/RabbitMqBundle#642]
Hi how i can create exchange, queue ? it's possible to use RabbitMqBundle for this ?

i must say i have read all doc, and i can see only speaking abort producer an consumer.

i want to use rabbitmq + mqtt to send to android device message. all exchange, and queue, binder have to be set by symfony on demande by api. it is possible to do this.

thank for any help

**Comment by mihaileu** [comment]
The queues/exchanges are created by running setup:fabric command, otherwise there are created when you start consumer.
If you want to do other stuff, you can try the api: https://rawcdn.githack.com/rabbitmq/rabbitmq-server/v3.8.17/deps/rabbitmq_management/priv/www/api/index.html

**Comment by xorgxx** [comment]
thank will look more in detail.
