### ISSUE TITLE
Purge command broken

### ISSUE THREAD

**Issue by innologi** [php-amqplib/RabbitMqBundle#644]
Hi,

The rabbitmq purge command is broken in v2.7.0 due to this change:
https://github.com/php-amqplib/RabbitMqBundle/commit/590e53129c06e9a7cb2a9f403024eed5817522f7#diff-b5ba74a19cc6229de08f6be0aba8420e579b6d0a2cd1433bfdc98bf18221118fR53-R60

The purge command inherits this from BaseConsumerCommand, but purge does not have a `messages` option, so it fails on the getOption() call from the change:

```
$ bin/console rabbitmq:purge default_consumer
13:02:04 CRITICAL [console] Error thrown while running command "rabbitmq:purge default_consumer". Message: "The "messages" option does not exist." ["exception" => Symfony\Component\Console\Exception\InvalidArgumentException
{ …}

,"command" => "rabbitmq:purge default_consumer","message" => "The "messages" option does not exist."]

The "messages" option does not exist.
```

Downgrading to v2.6.0 resolves the issue.

**Comment by mihaileu** [comment]
@andreea-anamaria  do you have time for looking intro ?

**Comment by mihaileu** [comment]
fixed in #650

**Comment by michaelphillpotts** [comment]
Hi

For this fix in https://github.com/php-amqplib/RabbitMqBundle/pull/650 is it necessary to include ext-pcntl in composer.json?

As I understand pcntl is not available on Windows platform and prevents installation. 
But v2.7.1 does not require ext-pcntl which is what I am using as a work around.

**Comment by Eloar** [comment]
@mihaileu @innologi this issue might be closed
