### ISSUE TITLE
Invalid frame type 21 

### ISSUE THREAD

**Issue by winus** [php-amqplib/RabbitMqBundle#645]
I have a RabbitMQ 3.8.17 installation with tls enabled on port 32038. Which is working perfectly with version 
php-amqplib/rabbitmq-bundle v1.15.1 (symfony 4.4)

Now I am building an new microservice based on symfony 5, and so, a newer version of the rabbitmqbundle and amqplib.

I'm an running into the following issue.

It looks like some data could not be decoder, or is not what it is expecting. 

Tried different connection strings, ssl_contexts etc.. cannot get it working. 
It does seem to decode the HEX partially ok.

`bin/console rabbitmq:consumer dead.letter --debug -vvv
< [hex]: 
0000  41 4D 51 50 00 00 09 01                            AMQP.... 

waiting for 10,10
waiting for a new frame
closing input
closing socket

In AbstractConnection.php line 585:
                                                    
  [PhpAmqpLib\Exception\AMQPInvalidFrameException]  
  Invalid frame type 21                             
                                                    

Exception trace:
  at /var/www/html/vendor/php-amqplib/php-amqplib/PhpAmqpLib/Connection/AbstractConnection.php:585
 PhpAmqpLib\Connection\AbstractConnection->wait_frame() at /var/www/html/vendor/php-amqplib/php-amqplib/PhpAmqpLib/Connection/AbstractConnection.php:636
 PhpAmqpLib\Connection\AbstractConnection->wait_channel() at /var/www/html/vendor/php-amqplib/php-amqplib/PhpAmqpLib/Channel/AbstractChannel.php:235
 PhpAmqpLib\Channel\AbstractChannel->next_frame() at /var/www/html/vendor/php-amqplib/php-amqplib/PhpAmqpLib/Channel/AbstractChannel.php:352
 PhpAmqpLib\Channel\AbstractChannel->wait() at /var/www/html/vendor/php-amqplib/php-amqplib/PhpAmqpLib/Connection/AbstractConnection.php:256
 PhpAmqpLib\Connection\AbstractConnection->connect() at /var/www/html/vendor/php-amqplib/php-amqplib/PhpAmqpLib/Connection/AbstractConnection.php:228
 PhpAmqpLib\Connection\AbstractConnection->__construct() at /var/www/html/vendor/php-amqplib/php-amqplib/PhpAmqpLib/Connection/AMQPStreamConnection.php:61
 PhpAmqpLib\Connection\AMQPStreamConnection->__construct() at n/a:n/a
 ReflectionClass->newInstanceArgs() at /var/www/html/vendor/php-amqplib/rabbitmq-bundle/RabbitMq/AMQPConnectionFactory.php:101
 OldSound\RabbitMqBundle\RabbitMq\AMQPConnectionFactory->createConnection() at /var/www/html/var/cache/dev/ContainerOa2jcj5/getOldSoundRabbitMq_Connection_DefaultService.php:25
 ContainerOa2jcj5\getOldSoundRabbitMq_Connection_DefaultService::do() at /var/www/html/var/cache/dev/ContainerOa2jcj5/App_KernelDevDebugContainer.php:447
 ContainerOa2jcj5\App_KernelDevDebugContainer->load() at /var/www/html/var/cache/dev/ContainerOa2jcj5/getOldSoundRabbitMq_Dead_LetterConsumerService.php:27
 ContainerOa2jcj5\getOldSoundRabbitMq_Dead_LetterConsumerService::do() at /var/www/html/var/cache/dev/ContainerOa2jcj5/App_KernelDevDebugContainer.php:447
 ContainerOa2jcj5\App_KernelDevDebugContainer->load() at /var/www/html/vendor/symfony/dependency-injection/Container.php:246
 Symfony\Component\DependencyInjection\Container->make() at /var/www/html/vendor/symfony/dependency-injection/Container.php:228
 Symfony\Component\DependencyInjection\Container->get() at /var/www/html/vendor/php-amqplib/rabbitmq-bundle/Command/BaseConsumerCommand.php:96
 OldSound\RabbitMqBundle\Command\BaseConsumerCommand->initConsumer() at /var/www/html/vendor/php-amqplib/rabbitmq-bundle/Command/BaseConsumerCommand.php:88
 OldSound\RabbitMqBundle\Command\BaseConsumerCommand->execute() at /var/www/html/vendor/symfony/console/Command/Command.php:299
 Symfony\Component\Console\Command\Command->run() at /var/www/html/vendor/symfony/console/Application.php:996
 Symfony\Component\Console\Application->doRunCommand() at /var/www/html/vendor/symfony/framework-bundle/Console/Application.php:96
 Symfony\Bundle\FrameworkBundle\Console\Application->doRunCommand() at /var/www/html/vendor/symfony/console/Application.php:295
 Symfony\Component\Console\Application->doRun() at /var/www/html/vendor/symfony/framework-bundle/Console/Application.php:82
 Symfony\Bundle\FrameworkBundle\Console\Application->doRun() at /var/www/html/vendor/symfony/console/Application.php:167
 Symfony\Component\Console\Application->run() at /var/www/html/vendor/symfony/runtime/Runner/Symfony/ConsoleApplicationRunner.php:56
 Symfony\Component\Runtime\Runner\Symfony\ConsoleApplicationRunner->run() at /var/www/html/vendor/autoload_runtime.php:35
 require_once() at /var/www/html/bin/console:11`

**Comment by mihaileu** [comment]
what are the libraries version, did you manage to bypass the issue ?

**Comment by winus** [comment]
The library is at versions

php-amqplib/php-amqplib              v3.0.0    Formerly videlalvaro/php-a...
php-amqplib/rabbitmq-bundle          2.7.0     Integrates php-amqplib wit...


I have not been able to bypass this.

**Comment by mihaileu** [comment]
@ramunasd  for 1.15.1 bundle version we were restricted to use "php-amqplib/php-amqplib":      "^2.6"
Are there any changes in php-amqplib 3.0 version, that can cause the above ?

**Comment by ramunasd** [comment]
From what I see looks like broker does not start connection handshake. I cannot tell more without full debug dump.

I can only guess that something is wrong with connection itself. Frame type 21 belongs to channel actions. Maybe Your connection is shared between processes somehow?

@mihaileu there was no changes in that part.

**Comment by winus** [comment]
The connection is made from a docker container with only 1 symfony 5 installation. There is only 1 consumer configured and running at the same time.

how can I make such a full debug dump?

**Comment by winus** [comment]
I have been testing and is seems to have something todo with the ssl context.
On the old version, I wanted to test using a DNS but forgot the ssl_context. Which then also gives a frame type 21 error.
After configuring the ssl_context { verify_peer: true }, it did work. 

After some debuggin I found the issue. The configuration is passed as a ssl_context. But within `PhpAmqpLib/Connection/AMQPStreamConnection.php:92` it should be context.

After changing 
`$context = isset($options['context']) ?
                         $options['context'] : null;`

to

`$context = isset($options['ssl_context']) ?
                         $options['ssl_context'] : null;`

It does work.

**Comment by winus** [comment]
Created pr https://github.com/php-amqplib/RabbitMqBundle/pull/648

**Comment by mihaileu** [comment]
closed by #648
