### ISSUE TITLE
requeue loop

### ISSUE THREAD

**Issue by ashton** [php-amqplib/RabbitMqBundle#65]
Hi,

I'm using rabbitmq to verify a status change in a third-party service, reading messages from a queue and sending them to a webservice that returns if it's status has changed or not. If there is no status change, I have to requeue the message to check it again later (I'm doing this just returning false in the consumer's execute method), but the message is again delivered to consumer  instantaneously, causing a loop until the message is dropped. Is there any way to avoid this behavior? Some way to postpone the delivery of the message to consumer or postpone the requeuing of the message?

**Comment by kolyadin** [comment]
@ashton any progress on this? Maybe any timeout?

**Comment by ramunasd** [comment]
You can delay message, please see [1]
 [1] https://www.rabbitmq.com/blog/2015/04/16/scheduling-messages-with-rabbitmq/
