### ISSUE TITLE
Unrecognized option queue_options_provider

### ISSUE THREAD

**Issue by zabidok** [php-amqplib/RabbitMqBundle#654]
Using php-amqplib/rabbitmq-bundle 2.8.0
in config/packages/old_sound_rabbit_mq.yaml i got such settings:

old_sound_rabbit_mq:
    connections:
        default:
            url: '%env(RABBITMQ_URL)%'
    consumers:
        task:
            connection: default
            exchange_options: { name: 'task', type: direct }
            queue_options:    { name: 'server1' }
            callback:         App\Consumer\BotTask
            queue_options_provider: App\Util\QueueOptions

but got error                                                                                                                                                   
  [Symfony\Component\Config\Definition\Exception\InvalidConfigurationException]                                                                                                                              
  Unrecognized option "queue_options_provider" under "old_sound_rabbit_mq.consumers.task". Available options are "auto_setup_fabric", "callback", "connection", "enable_logger", "exchange_options", "grace  
  ful_max_execution", "idle_timeout", "idle_timeout_exit_code", "qos_options", "queue_options", "timeout_wait".                                                                                              

where is problem?

**Comment by andrew-demb** [comment]
Option `queue_options_provider` should be used only within `dynamic_consumers`. 

Check docs here: https://github.com/php-amqplib/RabbitMqBundle/blob/d8b9457a4649cf92ae154a31ebdf321107f72cb7/README.md#dynamic-consumers
