### ISSUE TITLE
SF2 app with RabbitMqBundle failed when rabbitmq is stopped 

### ISSUE THREAD

**Issue by rouffj** [php-amqplib/RabbitMqBundle#69]
Hi @videlalvaro,

there is an issue with the RabbitMqBundle and php-amqplib. Here the steps to reproduce the bug:

1) bootstrap a Symfony2 app with `"oldsound/rabbitmq-bundle": "dev-master"` in composer.json
2) don't install rabbitmq server or stop it.
3) Try to display any page on the bootstrapped SF2 app with rabbitmq-bundle enabled

=> you will have the following exception:

```
ErrorException: Warning: stream_socket_client() [function.stream-socket-client]: unable to connect to tcp://vserver-jrouff.dev.sensio.net:5672 (Connection refused) in /Users/joseph.rouff/projects/insight/vendor/videlalvaro/php-amqplib/PhpAmqpLib/Connection/AMQPConnection.php line 80
```

It would be cool that RabbitMqBundle fail silently without any exception (or just a warning on the datacollector icon).

Thanks for you answer :).

**Comment by blixit** [comment]
thanks @stof for this later response ! you saved my time
