### ISSUE TITLE
Symfony deprecations

### ISSUE THREAD

**Issue by alcohol** [php-amqplib/RabbitMqBundle#707]
- [ ] Method "`Symfony\Component\DependencyInjection\Extension\ExtensionInterface::load()`" might add "`void`" as a native return type declaration in the future. Do the same in implementation "`OldSound\RabbitMqBundle\DependencyInjection\OldSoundRabbitMqExtension`" now to avoid errors or add an explicit `@return` annotation to suppress this message.
- [ ] Method "`Symfony\Component\DependencyInjection\Compiler\CompilerPassInterface::process()`" might add "`void`" as a native return type declaration in the future. Do the same in implementation "`OldSound\RabbitMqBundle\DependencyInjection\Compiler\___`" now to avoid errors or add an explicit `@return` annotation to suppress this message.
  - [ ] `RegisterPartsPass`
  - [ ] `InjectEventDispatcherPass`
- [ ] Method "`Symfony\Component\DependencyInjection\ContainerAwareInterface::setContainer()`" might add "`void`" as a native return type declaration in the future. Do the same in implementation "`OldSound\RabbitMqBundle\Command\BaseRabbitMqCommand`" now to avoid errors or add an explicit `@return` annotation to suppress this message.
- [ ] Method "`Symfony\Component\Console\Command\Command::initialize()`" might add "`void`" as a native return type declaration in the future. Do the same in child class "`OldSound\RabbitMqBundle\Command\___`" now to avoid errors or add an explicit `@return` annotation to suppress this message.
  - [ ] `BaseConsumerCommand`
  - [ ] `DeleteCommand`
- [ ] Method "`Symfony\Component\Console\Command\Command::configure()`" might add "`void`" as a native return type declaration in the future. Do the same in child class "`OldSound\RabbitMqBundle\Command\___`" now to avoid errors or add an explicit `@return` annotation to suppress this message.
  - [ ] `BaseConsumerCommand`
  - [ ] `AnonConsumerCommand`
  - [ ] `BatchConsumerCommand`
  - [ ] `ConsumerCommand`
  - [ ] `DeleteCommand`
  - [ ] `DynamicConsumerCommand`
  - [ ] `MultipleConsumerCommand`
  - [ ] `PurgeConsumerCommand`
  - [ ] `RpcServerCommand`
  - [ ] `SetupFabricCommand`
  - [ ] `StdInProducerCommand`

**Comment by alcohol** [comment]
Can be closed by #708 I think if it gets merged.

**Comment by mihaileu** [comment]
will look into

**Comment by mihaileu** [comment]
thx for the pr, it was merge
