### ISSUE TITLE
Add `--memory-limit` to `rabbitmq:rpc-server`

### ISSUE THREAD

**Issue by roslov** [php-amqplib/RabbitMqBundle#712]
There is the `--memory-limit` option in commands `rabbitmq:multiple-consumer` and `rabbitmq:consumer`. But such option does not exist in `rabbitmq:rpc-server`. Therefore, my RPC servers crash periodically because of memory leak.

Can you please add `--memory-limit` to `rabbitmq:rpc-server`?

**Comment by roslov** [comment]
I asked this question in already closed #545.

**Comment by mihaileu** [comment]
a PR would help here

**Comment by roslov** [comment]
Still actual.
