### ISSUE TITLE
Add "no_ack" consumer option (feature request)

### ISSUE THREAD

**Issue by andrey-tech** [php-amqplib/RabbitMqBundle#717]
Hello!

Please, add important configuration option for consumer `no_ack`. If set to `true`, automatic acknowledgement mode will be used by consumer. The default value is `false`.

We really need this option on our large project at the moment, but `no_ack` value is hardcoded to `false` in method `setupConsumer()` of classes:
  - `OldSound\RabbitMqBundle\RabbitMq\BaseConsumer`,
  - `OldSound\RabbitMqBundle\RabbitMq\BatchConsumer`,
  - `OldSound\RabbitMqBundle\RabbitMq\MultipleConsumer`.

E.g. https://github.com/php-amqplib/RabbitMqBundle/blob/master/RabbitMq/BaseConsumer.php#L71

```php
        $this->getChannel()->basic_consume($this->queueOptions['name'], $this->getConsumerTag(), false, false, false, false, [$this, 'processMessage']);
```

**Comment by mihaileu** [comment]
looking into

**Comment by mihaileu** [comment]
thx for your support, new tag was created: 2.13.0
