### ISSUE TITLE
Symfony 7.0 support

### ISSUE THREAD

**Issue by thenerka1** [php-amqplib/RabbitMqBundle#720]

**Comment by morawskim** [comment]
I have the same problem. 
Im my fork ([diff is here](https://github.com/php-amqplib/RabbitMqBundle/compare/master...morawskim:RabbitMqBundle:symfony7)) I added support for Symfony7, but my changes are not backward-compatible. 

The base class for command requires ContainerInterface from Symfony namespace, but ServiceLocator implements ContainerInterface from Psr namespace.
Thats why I have not yet create PR. I am looking for solution.
Also I need to test other commands.
