### ISSUE TITLE
Do Consumer have the timeout mechanism?

### ISSUE THREAD

**Issue by infernojaxon** [php-amqplib/RabbitMqBundle#8]
Hi, I'm using this bundle to deal with the data transfer, it really help me a lot.
I have several consumers, each use the bulk insert to get better performance.
But i find out every consumer hold some data because the amount didn't reach the batch size.
Will you add the timeout mechanism to Consumer?
Or there has any method can let Consumer know the queue situation?

**Comment by tiborb** [comment]
close because the question has been answered
