### ISSUE TITLE
Can not set 'x-message-ttl' in arguments in queue_options

### ISSUE THREAD

**Issue by phillpafford** [php-amqplib/RabbitMqBundle#80]
Following the example here:

queue_options:    {name: 'upload-picture', arguments: {'x-ha-policy': ['S', 'all']}}

I'm trying to do:

queue_options:    {name: 'upload-picture', arguments: {'x-message-ttl': 3600000}}

as I'm trying to set the message ttl for one hour

**Comment by Apostropher** [comment]
I'm seeing this issue. Is there a fix for this, 7 years later?

**Comment by Apostropher** [comment]
Nevermind, it seems to work even though the rabbitmq web console displays the value as a string.

**Comment by ramunasd** [comment]
Already possible using `$additionalProperties`.
