### ISSUE TITLE
Reconnect if connection is closed

### ISSUE THREAD

**Issue by starvim** [php-amqplib/RabbitMqBundle#83]
I have a consumer that once started performs some time-consuming operations and then tries to write to Rabbit. If the connection was closed by RabbitMQ server, then the application crashes with:

Notice: fwrite(): send of 31 bytes failed with errno=104 Connection reset by peer in vendor/videlalvaro/php-amqplib/PhpAmqpLib/Connection/AMQPConnection.php line 157

What can be done about it? Doesn't the bundle have possibility to re-connect to RabbitMQ server?

**Comment by Enleur** [comment]
@pierrre how can it help?

**Comment by SouthOfWest** [comment]
"Broken pipe or closed connection" exception on reconnect after 
Notice: fwrite(): send of 31 bytes failed with errno=104 Connection reset by peer in vendor/videlalvaro/php-amqplib/PhpAmqpLib/Connection/AMQPConnection.php line 157

**Comment by ramunasd** [comment]
Even if connection would be restored, You still need to perform at least subscribtions steps. Otherwise won't get any messages.
